### ISSUE TITLE
How do I access optionalCharacteristics?

### ISSUE THREAD

**Issue by volschin** [homebridge/HAP-NodeJS#121]
In Services.js is specified
`this.optionalCharacteristics = [];`
and filled from HomeKitTypes.js. A requied characteristic can be accessed by `getCharacteristic` or `setCharacteristic`. How this has to be done for the optional ones?

A small example:

``` javascript
var sensorCO2Service = new Service.CarbonDioxideSensor();

sensorCO2Service
  .getCharacteristic(Characteristic.CarbonDioxideDetected)
  .on('get', 'true');
  .getCharacteristic(Characteristic.CarbonDioxideLevel)
  .on('get', function(callback) {
    // return our current value
    callback(null, FAKE_SENSOR.getCO2());
  });
```

`CarbonDioxideDetected` works, `CarbonDioxideLevel` doesn't.

**Comment by KhaosT** [comment]
Try
```js
sensorCO2Service
  .getCharacteristic(Characteristic.CarbonDioxideDetected)
  .on('get', 'true');
sensorCO2Service
  .getCharacteristic(Characteristic.CarbonDioxideLevel)
  .on('get', function(callback) {
    // return our current value
    callback(null, FAKE_SENSOR.getCO2());
  });
```
?

**Comment by cflurin** [comment]
Http.js shows how to add an optional Characteristic:

````javascript
    lightbulbService
      .addCharacteristic(new Characteristic.Brightness())
      .on('set', this.setBrightness.bind(this));
````

**Comment by KhaosT** [comment]
@cflurin yeah, you're right... just found that from samples :)

**Comment by volschin** [comment]
Works, thank you. :+1:

**Comment by volschin** [comment]
I reopen this. Using addCharacteristic is the same way it is used in HomeKitTypes.js for required characteristics. You have no added value, no consistency check, that your added characteristic is allowed in this context.

I think there should be a user function for those optional characteristics, that check this is an allowed one with the data from `this.optionalCharacteristics = [];`.

**Comment by snowdd1** [comment]
@volschin I think you're right. 
@nfarina What happens to the `optionalCharacteristics` that are pushed into that array of the service definitions in *HomeKitTypes.js* ? Are the used somewhere? If not, volschin's idea of using them as a security check (issue a warning to the log/console e.g.) might prove helpful.

**Comment by nfarina** [comment]
Right now they're not used for anything - I wasn't sure how to handle them honestly besides putting them "in the code" for some visibility. I like the "security check" idea as long as you can bypass it somehow once you've been warned and you've decided you know what you're doing.

Perhaps `getCharacteristic` (and `getService`) should be throwing Errors anyway if the item doesn't exist instead of returning null, since they're used often for chaining calls. That way we could enhance the description of the Error when you ask for an _optional_ Characteristic, suggesting to add it first?

**Comment by snowdd1** [comment]
Sounds reasonable to me. An error saying "on is not a method of undefined" or such does not really suggest to add a characteristic first.

I suggest just to put a message to the console on `service.addCharacteristic()` if the UUID is not found in the optionals, and support your idea of throwing a defined exception if you try to `getCharacteristic` and isn't found! :+1:

**Comment by snowdd1** [comment]
If no one is working on that I'll give it a try!

synopsis:

If [`Service.prototype.getCharacteristic(Characteristic.Type)`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Service.js#L84) does not find the characteristic, AND it is no optionalCharacteristic match, it fails ungracefully and throws an error; programmer can use `addCharacteristic()` to add it anyhow, but will then receive a WARNING in console log entry.
If `Service.prototype.getCharacteristic(Characteristic.Type)` does not find the characteristic, BUT the type is in optionalCharacteristic, it adds the characteristic.type and returns it.

If [`Accessory.prototype.getService(Service.type)`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Accessory.js#L145) does not find the service in the accessory, it fails ungracefully with an exception.

details:
[`Service.prototype.addOptionalCharacteristic`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Service.js#L100) will return the added characteristic instead of undefined, for `getCharacteristic()` to return in turn.

**Comment by snowdd1** [comment]
Being at that, does anybody have an idea why the minimumValue is not usable in [`Characteristic.prototype.getDefaultValue`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Characteristic.js#L171) ?

Although in [`Characteristic.TargetTemperature `](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L1186) it is set to 10 (°C) in getDefaultValue it is 0.

Are we in the wrong `this`?

**Comment by cflurin** [comment]
@snowdd1: As an example I implemented a WindowCovering with optional Characteristics (Brightness and Saturation) in order to be able to use it with iOS 8.4.1. I don't see any disadvantages. This is also possible with the HK Simulator.
https://github.com/cflurin/homebridge-shims > FhemWindowCovering.js

**Comment by snowdd1** [comment]
> any disadvantages
The only I see is that Siri does only know the 'default' sets.

**Comment by cflurin** [comment]
Right! but just now it's work for me and soon (16th.) I'll change the code for iOS 9. :smile:

**Comment by snowdd1** [comment]
So PR #128 is there.

**Comment by KhaosT** [comment]
@snowdd1 Great :) I think it's not necessary to show warning when trying to add a non-optional characteristic to service... Would you mind to modify that part? Thx

**Comment by snowdd1** [comment]
Of course I can remove that, but this was actually the core/starting point  of the idea. 
@volschin: you raised this issue...! Is it enough to have getCharacteristic to return new optionals instead of adding them with addCharacteristic?

**Comment by snowdd1** [comment]
@KhaosT @nfarina 
Your opinions voiced here and in #128 are exactly opposing.
Could you agree which features are the wanted here?
- The warning if programmers try to add non-optional characteristics 
- or the ability to return a new optional characteristic on getCharacteristic with an not-yet-existing characteristic type, 
- or throwing an error on not-yet-existing non-optional characteristics?

**Comment by KhaosT** [comment]
@snowdd1 Sorry for the confusion, I think having the ability to return a new optional characteristic on get characteristic is the one I want to keep. Since HomeKit Accessory Simulator didn't prevent user from adding additional characteristic and HomeKit is happy with that, I think the warning for add non-optional characteristic is not necessary.

**Comment by snowdd1** [comment]
Done.

**Comment by mybays** [comment]
this issue is still open?
I write a fake AirQualitySensor service and want to get OptionalCharacteristic PM2_5Density,but he home app don`t show OptionalCharacteristic PM2_5Density

**Comment by ToddGreenfield** [comment]
@mybays try viewing in the Eve app. That seems to show most all of the air quality optional characteristics whereas the HomeKit app only shows CarbonMonoxide. Take a look at homebridge-airnow as an example.
