### ISSUE TITLE
Parsing accessory forever..

### ISSUE THREAD

**Issue by christofferbrask** [homebridge/HAP-NodeJS#127]
Running this setup on a raspberry pi model b.

When I running sudo Core.js it's just "Parsing accessory: Light_accessory.js" forever

I'm getting no error only warnings

"pi@raspberrypi ~/HAP-NodeJS $ sudo node Core.js

**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of                                                                                                                                Avahi.

**\* WARNING **\* Please fix your application to use the native API of Avahi!

**\* WARNING **\* For more information see <http://0pointer.de/avahi-compat?s=libd                                                                                                                               ns_sd&e=node>

**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not su                                                                                                                               pported (or only supported partially) in the Apple Bonjour compatibility layer o                                                                                                                               f Avahi.

**\* WARNING **\* Please fix your application to use the native API of Avahi!

**\* WARNING **\* For more information see <http://0pointer.de/avahi-compat?s=libd                                                                                                                               ns_sd&e=node&f=DNSServiceRegister>

HAP-NodeJS starting...

Parsing accessory: Light_accessory.js"

**Comment by legotheboss** [comment]
I think that means HAP is working. Did you try pairing the accessory with your phone?

**Comment by snowdd1** [comment]
If you want to see more "action" try starting it wit `DEBUG=* node Core.js`
Then it shows the debug log messages. 

Von meinem iPhone gesendet

**Comment by leoneleone** [comment]
I'm having the same issue:

"HAP-NodeJS starting..."
But it never reaches "HAP-NodeJS is listening"

None of my HomeKit iOS apps can find HAP-NodeJS (or in my case, homebridge) through "add device" via the apps. I'm convinced the issue lies with BridgedCore not completing the process to "HAP-NodeJS is listening".

**Comment by KhaosT** [comment]
@leoneleone Can you run the project with "DEBUG=* node BridgedCore.js " and see what happens there?

**Comment by snowdd1** [comment]
> EventedHTTPServer Server listening on port 51826 +0ms
> 
> It doesn't take me back to home/pi though. Just hangs after DEBUG output

It should print some debugging output if you try to connect to it using your homekit app (EVE e.g.)

**Comment by supermax45** [comment]
My problem was that my Pi was connected through Lan, while my iphone was on Wi-Fi. So they couldn't reach each other. With a Wi-Fi module on Pi everything worked flawless.

**Comment by snowdd1** [comment]
Then your wifi access point has an issue with multicasts or broadcasts. Had one of these too, and with it AirPlay was not reliably working.

**Comment by leoneleone** [comment]
Thanks for the input. Got the HAP server working now. 

Currently running into a problem while running Homebrige, same problem as detailed in this issue post:
https://github.com/nfarina/homebridge/issues/209

Adding Homebridge as an accessory via iOS results in "Adding Accessory Failed!"
I believe this is due to a ZWave door lock which is part of my ISY setup. This is probably why the "Homebridge" accessory can't be added. 

I'm still new to Raspberry Pi and Node so don't know how to solve the problem. 

I realise this is the wrong place to be asking about Homebridge specifics, but if anyone can have a look at the link and enlighten me, it would be greatly appreciated. 

Thanks guys
