### ISSUE TITLE
does anyone know how to use the Logs characteristic?

### ISSUE THREAD

**Issue by justme-1968** [homebridge/HAP-NodeJS#140]
does anyone know how to use the Logs characteristic? 

is there a defined format for history sensor values? how should the tlv8 data represented in HAP-NodeJS?

does anyone know how the elgato sensors transmit historic sensor data so that eve can display the graphs?

**Comment by desvdp** [comment]
have a look here: http://developer.xamarin.com/api/field/HomeKit.HMCharacteristicMetadataFormat.Tlv8/

**Comment by 0ff** [comment]
The tlv8-format is used throughout homekit, so you can find a working implementation in this very repo: `/lib/util/tlv.js`.
Of interest is the actual data stored in this format - I don't own any eve accessories unfortunately but I'm also interested in providing this data.
Actually, HAP-NodeJS might provide this data quite easily across multiple (if not all) platforms and accessories.

**Comment by luxus** [comment]
Wow that would be Great to See some Temperature sensors in Eve

**Comment by 0ff** [comment]
Hm. I fear this is not at all as easy as hoped. I got an eve weather today and well, they are doing some crazy custom stuff.
From what I can guess, they've created a custom Service that provides 2 Read-Only and 2 Write-Only Characteristics.
My best guess: they write sth. then get a response in the other char, write again, get another response.
This process actually takes quite a while on a few data points, I wonder how they limit that.
But anyway, I'm pretty sure they don't just use a Logs-characteristic and instead they implemented sth. completely custom :(

Anyone up for some reverse engineering? :)

**Comment by justme-1968** [comment]
i have just tried the same with a eve door sensor. here is a lot of custom services and characteristics. to bad :(

the eve app is really nice. the sensor not so.. my homematic sensors are much better. event ehe pushing of the current state works better with the fhem shim as with the eve sensor. so i will send it back.

**Comment by 0ff** [comment]
Oh, sad to hear that, but to be honest: I can totally understand your decision.
The hardware is plain out crap. I've had more problems connecting the Eve Weather to my Home than developing and connecting accessories from scratch. I think it's somewhat related to the BLE-requirements to save power, but hey that's not my problem.

On the bright side: I am able to fake a basic Eve with HAP-NodeJS now: ![](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/62625/433013/Zc3RXmNMIS5Wsie/upload.png)

I am able to send arbitrary log-values, though I have not yet understood how partial logs are requested (shouldn't be that big of a problem though, as we are on an IP Connection instead of BLE, I'd have no issues sending hundreds of kB of data).
What worries me is that the logs seem to be hard-coded, that is there are 3 values transmitted per log entry and these 3 values are used for each particular sensor respectively.
There's a bit of data I cannot make sense of right now so there might be some mapping hidden in there, but right now this would mean there's no way to make this protocol work across other devices (or, well at least not for any device that does not support the 3 sensors).
I do hope that Elgato put a bit of thought into this and allows for dynamic mapping, but we'll see.

**Comment by justme-1968** [comment]
that sounds absolutely great!

do you already have some code to share? i'd love to test this.

**Comment by justme-1968** [comment]
by the way: which characteristic do you use for the air pressure ?

**Comment by justme-1968** [comment]
any news on this?

**Comment by 0ff** [comment]
Ah, so sorry, this just went completely off my radar. No real progress so far but I’ll make sure to post my code tomorrow.

**Comment by 0ff** [comment]
There you go: https://gist.github.com/0ff/668f4b7753c80ad7b60b
Status: Works very limited. You can work reliably with temp, humidity and pressure.
Logs can be created, but not yet pointed to a specific time (I wasn't able to figure out their time format, should be doable though).
Also no interaction possible, i.e. the app will sometimes write to Write Trunk 1/2, but this is not handled. It does "paginate" through the logs if there are enough of them.

**Comment by justme-1968** [comment]
thanks. i'll have a look at it.

**Comment by Samfox2** [comment]
I extended my accessory with parts of your code just for "playing" purposes but the time of measurements in eve app is always 01.01.01. Did you make any progress with the time format?
