### ISSUE TITLE
Garage Door set status

### ISSUE THREAD

**Issue by rafus15** [homebridge/HAP-NodeJS#262]
Hi, i'm trying to implement this marvelous library up, to open my garage door, but i have a minor problem that i would like to fix, allow me to explain it:

My door is opened via a relay operated through the GPIO of a raspberry pi (b+). The board which controls the garage door motor is a pretty basic one, so i can only send a 0,5 seconds short circuit to "activate the motor". The door ends up following this basic algorithm:

If Short-circuit received door opens
If during the opening another short-circuit is received the door stops at the point which it was.
if stoped, if a short-Circuit is received the door will close.
if widely opened , if short-circuit received door closes.
if widely opened, passed 1,5 minutes the door closes.
if closing, if short-circuit recevied door changes course and opens again.

I'm using this code:

`var PythonShell = require('python-shell');

var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var garagedoor;

//configurable parameters
var serviceName = 'Garage Door Opener 3';
var serviceUUID = 'hap-nodejs:accessories:garagedoor3';

var GARAGE_DOOR = {
  opened: false,
  open: function() {
    console.log("Opening the Garage!");
    PythonShell.run('python/test.py', function (err) {
        if (err) throw err;
        console.log('finished');
    });
//garage.setCharacteristic(Characteristic.TargetDoorState, Characteristic.TargetDoorState.OPENED)
    GARAGE_DOOR.opened=true;
  },
  close: function() {
    console.log("Closing the Garage!!");
    //Characteristic.CurrentDoorState.value =false;
    Service.GarageDoorOpener.LockCurrentState=true;
    console.log("test-->" + Service.GarageDoorOpener.LockCurrentState );
     PythonShell.run('python/test.py', function (err) {
        if (err) throw err;
        console.log('finished');
    });
    GARAGE_DOOR.opened=false;
  },
  identify: function() {
    console.log("Identify the Garage");
    // nothing to do.
  }
};

//console.log("Garage door set as %s",GARAGE_DOOR.opened);

// Generate a consistent UUID for our GarageDoorOpener that will remain the same even when
// restarting our server.
var garageUUID = uuid.generate(serviceUUID);

// This is the Accessory that we'll return to HAP-NodeJS that represents our Garage opener.
var garage = exports.accessory = new Accessory(serviceName, garageUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
garage.username = "C2:5D:3F:EE:5E:FA";
garage.pincode = "000-15-150";

// listen for the "identify" event for this Accessory
garage.on('identify', function(paired, callback) {
  GARAGE_DOOR.identify();
  callback(); // success
});

// Add the actual Garage Opener Service and listen for change events from iOS.
// We can see the complete list of Services and Characteristics in `lib/gen/HomeKitTypes.js`
garage
  .addService(Service.GarageDoorOpener, "Garage Door")
  .setCharacteristic(Characteristic.TargetDoorState, Characteristic.TargetDoorState.OPENED) // force initial state to CLOSED
  .getCharacteristic(Characteristic.TargetDoorState)
  .on('set', function(value, callback) {

```
if (value == Characteristic.TargetDoorState.CLOSED) {
  GARAGE_DOOR.close();
  //Characteristic.TargetDoorState.CLOdSED
//callback();
  // now we want to set our garage "actual state" to be CLOSED so it shows as Closed in iOS apps
  garage
    .getService(Service.GarageDoorOpener)
.setCharacteristic(Characteristic.CurrentDoorState, Characteristic.CurrentDoorState.CLOSED);
```

callback();
    //garage.setCharacteristic(Characteristic.TargetDoorState, Characteristic.TargetDoorState.CLOSED)
    }
    else if (value == Characteristic.TargetDoorState.OPEN) {
      GARAGE_DOOR.open();
//Characteristic.TargetDoorState.OPENED
      //callback();
      // now we want to set our garage "actual state" to be OPEN so it shows as Open in iOS apps
      Service.GarageDoorOpener.LockCurrentState=false;
    Service.GarageDoorOpener.LockTargetState=false
    garage
    //garage.setCharacteristic(Characteristic.TargetDoorState, Characteristic.TargetDoorState.CLOSED)
    .getService(Service.GarageDoorOpener)
    .setCharacteristic(Characteristic.CurrentDoorState, Characteristic.CurrentDoorState.OPENED);

```
callback();
}
```

  });`

Where test.py is an extremely basic pyhton script which activates a relay during 0,5 seconds, sending the needed 0,5 seconds short circuit.

The problem is that in homekit i have "Opened" and "Closed" status, and i would like to be able to set the status, for example (the most common use case).

I send a open command through siri --> The door opens (the status in homekit is "opened") --> After 1,5mins the status changes to closing --> After 20 seconds (time that the door takes to complete the closing travel) the status changes to closed.

This way the system would be much more coherent, because right now i have my door closed but homekit says "opened" just because it only changes status when i send a command to activate the relay.

I don't know if i was very clear in my explanation, i'll reexplain everything that you don't get if needed.

Thank you so much for your time

Rafius15

**Comment by nagybalint001** [comment]
Hi,
We have something similar problem here.
We use HomeKit to control an "outdoor motorized gate", so it's not a garage door, but something similar. Because of the fact that the electronics are outdoor, it is not easy to wire the raspberry pi with the controller, with AC and to connect to the internet. So we chose to use one of the remotes and connect a relay to the specific button with soldering wires to the two side of the button; and replacing the battery with a 12 Volt power supply. The raspberry sends a short signal to the relay, which emulates the pressing of the button on the remote.
In this way we placed the raspberry inside the house. 
We have 4 possible options if we "press the button":
 - if the gate is closed completely, it starts opening
 - if the gate is fully open, it starts closing
 - if the gate is moving, it stops
 - if the gate is not closed, and not open, it starts to move the opposite way, it used to move before stopping.
Also this system is capable of sensing whether the gate is fully closed or not with a magnetic "door switch".

Now the problem is similar to your.
Somehow we want to force the homekit app to refresh the status of the gate, because we don't only control it through HomeKit, we also use other remotes and a web app also.

We would like to use the sensor to detect the state of the door and then refresh the state on the iPhone Home app.

Maybe someone will be able to help us

Thank you for your time!

**Comment by olistic** [comment]
Hey guys, if it helps I'm sharing the code I used for my motorized gate: https://gist.github.com/olistic/c7abaac2926b5311674e25c76b7f61d9.

The gate behaviour is similar to @nagybalint001's, with the addition that it locks itself for 2 minutes every time it is completely open or closed. That means that for opening/closing it when locked, you have to press the remote button twice (the first press unlocks it).

I have the gate wired to a relay, which I operate through a Particle Photon. I haven't wired a sensor yet, but I keep track of the state of the gate in the code which is good enough for now.

**Comment by nagybalint001** [comment]
Hi,
Thank you for your fast response.
I quickly read the code you posted and it seems like it contains the information, I was missing.

Did you try this with the new iOS10 Home App?
Or which HomeKit app you use? Because in the new Home app I only saw Open/Opening/Closed/Closing status information (no Stopped status, and the Opening/Closing status was showing "magically" and after a manual refresh it changed to Open/Closed).

**Comment by olistic** [comment]
No, I decided not to install the beta this time so I'm using Insteon+. Although I'm responding with 5 different states, I never saw anything other than Open/Closed in the app. However, if the state is anything but Closed, the gate reports as Open, which is fine for my use case.

If that were the case and the Stopped state no longer existed, I would reply with `Opening` when the state is `STOPPED_CLOSING` and `Closing` when the state is `STOPPED_OPENING`, because those would be the next states the gate would be when the button is pressed again.

**Comment by flogiston** [comment]
Hi!
I also implemented an external gate as `GarageDoorOpener`, but I have the following problem.

When I use the HomeKit app on the phone, the gate opens just fine, i.e. I send the `Characteristic.CurrentDoorState.OPENING` and then after the gate closing time passes, I send the `Characteristic.CurrentDoorState.OPEN`. The app shows the states just fine. The same goes for closing.

Now, when I detect an external gate open event (i.e. from a remote) and send the same sqeuence of notifications as above, the app instantly shows "Gate closing" and the wheel spins until I press the button. Then the opening sequence happens again (with closed status at the end).

It looks like the app's state goes crazy when the external event comes in, i.e. the app tries to impose it's last known state (closed) when an 'open' event doesn't come from an interaction within the app.

Any tips? Thanks in advance :)

P.S. There is a nice GPIO library for node.js -- `rpio`, so that you don't have to call any subprocesses written in other languages.

**Comment by exsilium** [comment]
@nagybalint001 Interesting hack around soldering the relay around to the actual remote :)

I'm also working on automating motorized gates but I use XBee with a relay to send the 125ms pulse to the contacts to activate the motor. However, I don't see a way reliably telling if the gate is opened or closed state because additional sensors would be needed to read back the state. I just use the on/off characteristic button as an activator which is programmed to go back to the "Off" state.

If you'd add couple of Reed switches to the project or if you can get the signal from the gate controller, you could use the same approach and send the state back with the XBee and update the state on the homebridge side.

Perhaps you'd be interested in helping to extend the project(s):

https://github.com/exsilium/pxbee-trigger -> hardware that is placed inside the gate opener, I use a cheap KIS3R33S based buck down converter to get 7-24V (whatever the gate opener uses) to 5V(USB) (It only currently triggers a relay, it is not programmed to read back and send back any states.. that part should be implemented separately).

https://github.com/exsilium/homebridge-xbee -> this actually does sending the signal to the XBee that is housed at the gate controller but extending it a bit could be used to read back the states and update the accessory states accordingly.

I'm interested in implementing the states in the most generic way possible so that it would be easy to adapt the accessory to swing gates, slide gates as well as garage door openers. Also trying to keep the hardware side as small as possible so that ideally it can easily fit to the gate/door controller box.

Cheers!

**Comment by theg1nger** [comment]
Running into these same difficulties. Haven't been able to find a solution yet. Setting CurrentDoorState based off of a sensor reading seems to go wonky. It goes from "closed" to "closing" when the sensor is tripped. My thought was it would go from "closed" to "open".

```
 84 //set the final state of the garage door
 85 function finishState(){
 86         readSensor();
 87         if (FAKE_GARAGE.opened){
 88                 console.log("finished State value is "+FAKE_GARAGE.opened+" should be true");
 89                 garage
 90                  .getService(Service.GarageDoorOpener)
 91                  .setCharacteristic(Characteristic.CurrentDoorState, Characteristic.CurrentDoorState.CLOSED);
 92
 93         }else{
 94                 console.log("finished State value is "+FAKE_GARAGE.opened+" should be false");
 95                 garage
 96                  .getService(Service.GarageDoorOpener)
 97                  .setCharacteristic(Characteristic.CurrentDoorState, Characteristic.CurrentDoorState.OPEN);
 98         }
 99
100 }
```
Sadly it goes from "Closed" to "Closing" based on true or false of the reed sensor... Weird.

**Comment by snowdd1** [comment]
That is the interpretation of the home app: the target state is "closed", and the current is "open", so it thinks it should be "closing". You just need to address the target state as well. elgato Eve app shows the current position state as is reported by the plugin, not based on differences between current and target states.

**Comment by doglover129** [comment]
@snowdd1 any idea on how one may properly over ride the target state? I'm experiencing all issues users listed above

**Comment by snowdd1** [comment]
Sure, it is an characteristic just as the others. You need to set its value to the same value as the current state if the motion is done, or if you want to show the correct motion, in the moment the motion is about to start - together with the current state to "opening" or "closing".

**Comment by theg1nger** [comment]
@snowdd1 I feel like I'm almost there. I understand the need to set the target door state so that it is the same of the current door state. The issue I have now is that by manually setting it, it is tripping the relay. Is that because the of ".on("set", function(value, callback)" part of the code that is triggered by the home app? 

How would I update the target door state without the code thinking that I am pressing a button?

**Comment by KhaosT** [comment]
Check updateValue function on characteristic

**Comment by jmgutierrezc1** [comment]
I found exactly the same problem and understand that the target state has to be updated when the door is "manually" opened or closed. have not found a solution to change in the *.js code to solve this problem.
