### ISSUE TITLE
Thermostat_accessory - get current temp question

### ISSUE THREAD

**Issue by ColinRobbins** [homebridge/HAP-NodeJS#310]
Hello,
I'm struggling with the new format API Thermostat_accessory is using.
I'm using it to control a set of  LightwaveRF thermostats.   I have a set of lights / switches working too.

I can set the temperature, in the "execute" function, and it sets everything nicely.
(I'm using a dgram to push a UDP message to the LightwaveRF WIFI bridge)

The challenge is how do I inform the home bridge of the current temperature.
I can obtain the current temp, via a UDP listener on port 9761,
1) How do I find the appropriate object in homebridge to set the appropriate value?
2) How do I get home bridge to read this value?

Thanks for any help (bit of a novice I'm afraid).

I'm good a plagiarism, so a pointer at example code doing something similar would be great!

Cheers,

**Comment by bluntiless** [comment]
Hi Colin,
I have some LightwaveRF Trv's and a thermostat. I was wondering if your set up currently uses Siri to set the target temperature ? If so could you tell me how you added this to HAP-NodeJS please.

Kind regards 

Wayne

**Comment by ColinRobbins** [comment]
Hello Bluntiless.

Yes I did get it to work with Siri - took a while.   I am in the process of documenting what I did, and will post back here.   Please bear with me,  Should be able to do it next weekend.

**Comment by bluntiless** [comment]
Thanks Colin,

I am not even a novice but also good at plagiarising. Thank heavens for GitHub

**Comment by kentlefley** [comment]
Hi Colin:

Looking forward to your post.  I am having similar issues with the thermostat_accessory

**Comment by ColinRobbins** [comment]
I found a solution.

In short, I turned the problem upside down.  Rather than try to find an accessory when an event occurred, I broke into two separate events. One to record the current accessory temp,  from a different Node.js script.  This meant I can then read the temp when I want.
I then created a time in bridge.js, and looped through all accessories.  I matched accessories based on serial number, then performed a read of the temperature.  

I've documented this in detail in my blog [Smart Home Project – HomeKit and LightwaveRF Integration](https://cybermatters.info/2016/11/15/smart-home-project-homekit-and-lightwaverf-integration/) with code fragments.

**Comment by bluntiless** [comment]
Hi ColinRobbins.

I am still working on adding my Home Thermostat and TRV'S to HAP-NodeJS. While I was looking at your blog, I noticed that you mentioned that If you send too many commands, too quickly, to the LightwaveRF hub, it chooses to ignore them. I believe that this is because since iOS 10 and the release of Home app, it sends both an 'on' and a 'dim' message for operations on a light.  In addition to this It seems they've changed the LightwaveRF Link firmware (U2.93T or U2.93Z), so that you can't send messages as frequently as was previously possible.
Can you try changing the delay (in milliseconds) in lib/util/lightwave.js:
 setInterval(sendFromQueue, 250);
I would suggest trying 800 and seeing if that fixes the problem. One final thing to try also, if you haven't already is updating to the latest version of HAP-NodeJS. I believe that this issue has been addressed in this latest version.

**Comment by ColinRobbins** [comment]
Hi, thanks for the tip. 
I'm not using the lightwave.js - I programmed it myself directly using UDP.
I'm using a 1 second delay, and it all seems fine.
Cheers.

**Comment by TeraJaQ** [comment]
Hi i've modified the thermostat_accessory.js to use with mqtt and it control the heating...

var RoomTemperature = 50.0;
var TargetTemp = RoomTemperature;
//var currentHCS = 0;

// MQTT Setup
var mqtt = require('mqtt');
console.log("Connecting to MQTT broker...");
var mqtt = require('mqtt');
var options = {
  port: 1883,
  host: '192.168.1.39',
  clientId: 'RoomTemperatureSensor'
};
var client = mqtt.connect(options);
console.log("Thermostat Connected to MQTT broker");

client.subscribe('TempCamera');
client.on('message', function(topic, message) {
  //console.log(parseFloat(message));
  RoomTemperature = parseFloat(message);
});

//client.subscribe('CurrentHeatingCoolingState');
//client.on('message',function(topic, message){
//  currentHCS = parseFloat(message);
//});


// HomeKit types required
var types = require("./types.js")
var exports = module.exports = {};



var TEMP_SENSOR = {
  getTemperature: function() {
    client.publish('info','ds18b20');
    console.log("Ottengo la temperatura in camera");
    return TEMP_SENSOR.currentTemperature; 
  },
  randomizeTemperature: function() {
    TEMP_SENSOR.currentTemperature = RoomTemperature;
    console.log(TEMP_SENSOR.currentTemperature); 
//},
//  getCurrentHeatingCoolingState: function() {
//   client.publish('info','getCurrHCS');
//   console.log("Ottengo le impostazioni del termostato");
//   return TEMP_SENSOR.currentHeatingCoolingState;
//},
//  randomizeHeatingCoolingState: function() {
//    TEMP_SENSOR.currentHeatingCoolingState = currentHCS;
 }
}

var execute = function(accessory,characteristic,value){ 
	
	console.log("executed accessory: " + accessory + ", and characteristic: " + characteristic + ", with value: " +  value + "."); 
	
	if (characteristic == 'Target Temperature'){
	TargetTemp = value;
	client.publish('TargetTemperature', String(TargetTemp)); //Send via  MQTT Target Temperature to ESP8266 Thermostat
	TEMP_SENSOR.targetTemperature = value;}
	
	if (characteristic == 'Target HC'){
	client.publish('TargetHC',String(value));
 		if (value == '0'){
		console.log("OFF");
		TEMP_SENSOR.currentHeatingCoolingState = 0;
		}
 		if (value == '1'){
		console.log("CALDO");
		TEMP_SENSOR.currentHeatingCoolingState = 1;
		}
 		if (value == '2'){
		console.log("FREDDO");
		TEMP_SENSOR.currentHeatingCoolingState = 2;
		}
 		if (value == '3'){
		console.log("AUTO");
			if (TEMP_SENSOR.targetTemperature == TEMP_SENSOR.currentTemperature)
				TEMP_SENSOR.currentHeatingCoolingState = 0;
			if (TEMP_SENSOR.targetTemperature > TEMP_SENSOR.currentTemperature)
				TEMP_SENSOR.currentHeatingCoolingState = 1;
			if (TEMP_SENSOR.targetTemperature < TEMP_SENSOR.currentTemperature)
                                TEMP_SENSOR.currentHeatingCoolingState = 2;
		}  
	}
	
//	if (characteristic == 'Current HC'){
//	client.publish('CurrentHC','status?');
//	value = currentHCS; 
//	}
}

exports.accessory = {
  displayName: "ESP ThermoS",
  username: "CA:3E:BC:4D:2E:F2",
  pincode: "031-45-154",
  services: [{
    sType: types.ACCESSORY_INFORMATION_STYPE, 
    characteristics: [{
      cType: types.NAME_CTYPE, 
      onUpdate: null,
      perms: ["pr"],
      format: "string",
      initialValue: "Termostato",
      supportEvents: false,
      supportBonjour: false,
      manfDescription: "Bla",
      designedMaxLength: 255    
    },{
      cType: types.MANUFACTURER_CTYPE, 
      onUpdate: null,
      perms: ["pr"],
      format: "string",
      initialValue: "DIY",
      supportEvents: false,
      supportBonjour: false,
      manfDescription: "Bla",
      designedMaxLength: 255    
    },{
      cType: types.MODEL_CTYPE,
      onUpdate: null,
      perms: ["pr"],
      format: "string",
      initialValue: "Rev-1",
      supportEvents: false,
      supportBonjour: false,
      manfDescription: "Bla",
      designedMaxLength: 255    
    },{
      cType: types.SERIAL_NUMBER_CTYPE, 
      onUpdate: null,
      perms: ["pr"],
      format: "string",
      initialValue: "A1S2NASF88EW",
      supportEvents: false,
      supportBonjour: false,
      manfDescription: "Bla",
      designedMaxLength: 255    
    },{
      cType: types.IDENTIFY_CTYPE, 
      onUpdate: null,
      perms: ["pw"],
      format: "bool",
      initialValue: false,
      supportEvents: false,
      supportBonjour: false,
      manfDescription: "Identify Accessory",
      designedMaxLength: 1    
    }]
  },{
    sType: types.THERMOSTAT_STYPE, 
    characteristics: [{
      cType: types.NAME_CTYPE,
      onUpdate: null,
      perms: ["pr"],
      format: "string",
      initialValue: "Termostato", //nome device
      supportEvents: false,
      supportBonjour: false,
      manfDescription: "Bla",
      designedMaxLength: 255   
    },{
      cType: types.CURRENTHEATINGCOOLING_CTYPE,
//      onUpdate: function(value) { console.log("Change:",value); execute("Thermostat", "Current HC", value); },
      onUpdate: function (callback) {
//	TEMP_SENSOR.getCurrentHeatingCoolingState();
//      TEMP_SENSOR.randomizeHeatingCoolingState();	
	callback (TEMP_SENSOR.currentHeatingCoolingState)},
      onRead: function (callback) {
//      TEMP_SENSOR.getCurrentHeatingCoolingState();
//      TEMP_SENSOR.randomizeHeatingCoolingState();
	callback (TEMP_SENSOR.currentHeatingCoolingState)},
      perms: ["pr","ev"],
      format: "int",
      initialValue: 0,
      supportEvents: false,
      supportBonjour: false,
      manfDescription: "Current Mode",
      designedMaxLength: 1,
      designedMinValue: 0,
      designedMaxValue: 2,
      designedMinStep: 1,    
    },{
      cType: types.TARGETHEATINGCOOLING_CTYPE,
      onUpdate: function(value) { console.log("Change:",value); execute("Thermostat", "Target HC", value); },
      perms: ["pw","pr","ev"],
      format: "int",
      initialValue: 0,
      supportEvents: false,
      supportBonjour: false,
      manfDescription: "Target Mode",
      designedMinValue: 0,
      designedMaxValue: 3,
      designedMinStep: 1,
    },{
      cType: types.CURRENT_TEMPERATURE_CTYPE,
      onUpdate: function(callback) { TEMP_SENSOR.getTemperature();TEMP_SENSOR.randomizeTemperature(); callback (TEMP_SENSOR.currentTemperature); },
      onRead: function(callback) { TEMP_SENSOR.getTemperature(); TEMP_SENSOR.randomizeTemperature(); callback (TEMP_SENSOR.currentTemperature); },
      perms: ["pr","ev"],
      format: "int",
      initialValue: function(callback) {callback (TEMP_SENSOR.currentTemperature);},
      supportEvents: false,
      supportBonjour: false,
      manfDescription: "Current Temperature",
      unit: "celsius"
    },{
      cType: types.TARGET_TEMPERATURE_CTYPE,
      onUpdate: function(value) { console.log("Change:",value); execute("Thermostat", "Target Temperature", value); },
      perms: ["pw","pr","ev"],
      format: "int",
      initialValue: 20,
      supportEvents: false,
      supportBonjour: false,
      manfDescription: "Target Temperature",
      designedMinValue: 16,
      designedMaxValue: 38,
      designedMinStep: 1,
      unit: "celsius"
    },{
      cType: types.TARGET_RELATIVE_HUMIDITY_CTYPE,
      onUpdate: function(value) { console.log("Change:",value); execute("Thermostat", "Target Relative Humidity", value);  },
      perms:["pw","pr","ev"],
      format: "int",
      initialValue: 40,
      supportEvents: false,
      supportBonjour: false,
      manfDescription: "Target Humidity",
      designedMinValue: 35,
      designedMaxValue: 100,
      designedMinStep: 5,
      unit: "percentage"
    },{
      cType: types.CURRENT_RELATIVE_HUMIDITY_CTYPE,
      onUpdate: function(value) { console.log("Change:",value); execute("Thermostat", "Current Relative Humidity", value);  },
      perms:["pr","ev"],
      format: "int",
      initialValue: 0,
      supportEvents: false,
      supportBonjour: false,
      unit: "percentage"
    },{
      cType: types.TEMPERATURE_UNITS_CTYPE,
      onUpdate: function(value) { console.log("Change:",value); execute("Thermostat", "Unit", value); },
      perms: ["pr","ev"],
      format: "int",
      initialValue: 0,
      supportEvents: false,
      supportBonjour: false,
      manfDescription: "Unit"
    }]
  }]
}

 setInterval(function() {
  TEMP_SENSOR.getTemperature();
  TEMP_SENSOR.randomizeTemperature();
//  TEMP_SENSOR.getCurrentHeatingCoolingState();
//  TEMP_SENSOR.randomizeHeatingCoolingState();
// update the characteristic value so interested iOS devices can get notified 
 }, 40000);

**Comment by TeraJaQ** [comment]
the heating control is fully functional ...you can see i've added the humidity characteristic but i can't find a solution to subscribe to multiple topic on a single accessory...i've tried with the current heating cooling state but when is activated the 'message' var confuse my accessory..

**Comment by bluntiless** [comment]
Hi Colin, hope you are well.

I was just enquiring whether your thermostats and TRV's are still working as mine have recently stopped! I think it is because of a recent Lightwave wifi link update.

Also I would like to pick your brain, as I understand you work with internet security!
If you can help at all let me know. It is with regards to a recent spell of broadband suspensions by Sky.

Best wishes

Wayne Wright

Sent from my iPad

On 7 Nov 2016, at 13:50, Colin Robbins <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello Bluntiless.

Yes I did get it to work with Siri - took a while. I am in the process of documenting what I did, and will post back here. Please bear with me, Should be able to do it next weekend.

**Comment by ColinRobbins** [comment]
Hello Wayne,

Yes my TRVs did all stop working - I thought it was me!
I have them all working again - using the "resave heating schedules" under "settings" in the iPhone app seemed to be the cure.

On the security point, why not drop me an email at colin.robbins AT nexor.com.

Cheers.

**Comment by bluntiless** [comment]
Hi again and thanks for your quick response!

Occasionally when trying to view my Raspberry Pi HAP-NodeJS server screen on VNC Viewer via iPad, the Pi will not allow access with the correct username and password. It tells me that the username and password are incorrect and as a result, Sky detect these attempts to access the Pi via SSH and suspend my broadband service. These are the logs they have sent me:


Sep 16 10:34:38 this_host sshd[3896]: Invalid user pi from 5.71.109.243

Sep 16 10:34:38 this_host sshd[3898]: Invalid user pi from 5.71.109.243

Sep 16 10:34:39 this_host sshd[3896]: Failed password for invalid user pi from5.71.109.243 port 50960<tel:50960> ssh2

Sep 16 10:34:40 this_host sshd[3896]: Connection closed by 5.71.109.243 [preauth]

Sep 16 10:34:40 this_host sshd[3898]: Failed password for invalid user pi from5.71.109.243 port 50964<tel:50964> ssh2

Sep 16 10:34:40 this_host sshd[3898]: Connection closed by 5.71.109.243 [preauth]

The log above is an example of multiple unauthorised access attempts targeting an SSH (port 22) server on a private network and originating from your Sky Broadband connection. This activity is likely to be caused by the security of a device on your network being compromised

As this activity is in breach of Sky's Acceptable Use Policy we request that you refrain from any activity which may compromise these terms and conditions.

It does seem to coincide with my attempts to view my Pi and the “from” IP address and “connection closed by” IP address are the same, so I assume that this is the issue. Very strange to me as it seems to be just on my LAN connection, not the WAN.

Let me know your thoughts Colin as they are convinced it is a virus, malware or a bot.

Kind regards


Wayne



Sent from my iPhone

On 20 Sep 2017, at 15:57, Colin Robbins <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello Wayne,

Yes my TRVs did all stop working - I thought it was me!
I have them all working again - using the "resave heating schedules" under "settings" in the iPhone app seemed to be the cure.

On the security point, why not drop me an email at colin.robbins AT nexor.com<http://nexor.com>.

Cheers.
