### ISSUE TITLE
HAP-NodeJS IR

### ISSUE THREAD

**Issue by Flawl3ssSWE** [homebridge/HAP-NodeJS#361]
Hi!
I wonder if you possibly could control rgb bulbs like this one: [http://www.ebay.com/itm/E27-Dimmable-RGB-LED-light-Color-Changing-Bulb-with-Remote-Control-85-265V-/182048657709?hash=item2a62f2112d:g:A3UAAOSwh-1W3-2T#rwid](url) with the help of a ir reciver link: [http://www.ebay.com.au/itm/1Pcs-1X-Transmitter-Remote-Infrared-Receiver-Control-Module-For-Arduino-Ic-O-/282283687429?hash=item41b96b3e05:g:-8sAAOSwo4pYHeS1](url) I would like to control them with HAP-NodeJS and a Raspberry Pi so I can change color with my phone. I wonder as well if some one of you have done it and please can send me the code for it. Because I don't know how to program in Java!

Pre thanks!!!!!

**Comment by OczkoSX** [comment]
Maybe decode codes from remote control, buy transmiter and connect it to RPi? Thats the way i would do it

**Comment by Flawl3ssSWE** [comment]
Thanks for the answer I have found a video on youtube [https://youtu.be/u_bH7e-OgQo](url) I wonder if it will work if you change up the code a bit. So you can use the slider to control the color. It should theoretically work but as I have said I don't know how to get the transmiter etc to work but I will probably find a solution some time in the future. If you have any experience please help me!

Pre Thanks

**Comment by OczkoSX** [comment]
None of the links are working for me (strange github error). You need to check whether the remote sends Hue, Saturation, Brightness / RGB values or defined presets (just like colors of buttons). If the first one - it's easy to do, if the second - you will be in trouble (you can send only predefined values)

**Comment by Flawl3ssSWE** [comment]
Ok thanks!
The links work if you copy them with CTRL+C or CMD+C.

**Comment by OczkoSX** [comment]
I'm on phone and can't do it

Wysłane z iPhone'a

Dnia 11.12.2016 o godz. 12:55 Flawl3ssSWE <notifications@github.com> napisał(a):

**Comment by Flawl3ssSWE** [comment]
ohh try to hold the text down and see if copy comes up then go to your browser of choise and paste it

**Comment by TeraJaQ** [comment]
try use AnalysIR to decode the IR signal from the remote...
i've used this software to make a reverse engineering on the Air Conditioner IR remote and at the end i've put the code on a nodemcu (WemosD1 with an IR led connected) and via mqtt I control air conditioner from the thermostat accessory..

**Comment by Flawl3ssSWE** [comment]
thanks

**Comment by TeraJaQ** [comment]
this is my test RGB led accessory... the rgb led's are connected to an NodeMCU and listen MQTT message...and convert brightness, hue and saturation in Red, Green and Blu value...

// MQTT Setup
var mqtt = require('mqtt');
console.log("Connecting to MQTT broker...");
var mqtt = require('mqtt');
var options = {
  port: 1883,
  host: '192.168.1.39',
  clientId: 'RGB Wifi LED'
};
var client = mqtt.connect(options);
console.log("Wifi Light Connected to MQTT broker");


var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;

// here's a fake hardware device that we'll expose to HomeKit
var RGBLED = {
  powerOn: false,
  brightness: 100, // percentage
  hue: 0,
  saturation: 0,

  setPowerOn: function(on) { 
    console.log("Turning Office Light %s!", on ? "on" : "off");
    if (on) {
	client.publish('RGBLedPower','1');
	RGBLED.powerOn = on;
   	} 
    else {
	client.publish('RGBLedPower','0');
      	RGBLED.powerOn = false;   
   }
  },

  setBrightness: function(brightness) {
    console.log("Setting light brightness to %s", brightness);
    client.publish('ledBrightness',String(brightness));
    RGBLED.brightness = brightness;
  },
  setHue: function(hue){
    console.log("Setting light Hue to %s", hue);
    client.publish('ledHue',String(hue));
    RGBLED.hue = hue;
  },
  setSaturation: function(saturation){
    console.log("Setting light Saturation to %s", saturation);
    client.publish('ledSaturation',String(saturation));
    RGBLED.saturation = saturation;
  },
  identify: function() {
    console.log("Identify the light!");
  }
}

// Generate a consistent UUID for our light Accessory that will remain the same even when
// restarting our server. We use the `uuid.generate` helper function to create a deterministic
// UUID based on an arbitrary "namespace" and the word "RGBLED".
var lightUUID = uuid.generate('hap-nodejs:accessories:RGBLED');

// This is the Accessory that we'll return to HAP-NodeJS that represents our fake light.
var light = exports.accessory = new Accessory('RGB Led', lightUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
light.username = "FF:FF:FF:FF:FF:1B";
light.pincode = "031-45-154";

// set some basic properties (these values are arbitrary and setting them is optional)
light
  .getService(Service.AccessoryInformation)
  .setCharacteristic(Characteristic.Manufacturer, "DIY RGB Lamp")
  .setCharacteristic(Characteristic.Model, "RGB LED on NodeMcu")
  .setCharacteristic(Characteristic.SerialNumber, "AA-1234");

// listen for the "identify" event for this Accessory
light.on('identify', function(paired, callback) {
  RGBLED.identify();
  callback(); // success
});

// Add the actual Lightbulb Service and listen for change events from iOS.
// We can see the complete list of Services and Characteristics in `lib/gen/HomeKitTypes.js`
light
  .addService(Service.Lightbulb, "Rgb Led") 				// services exposed to the user should have "names" like "Fake Light" for us
  .getCharacteristic(Characteristic.On)
  .on('set', function(value, callback) {
    RGBLED.setPowerOn(value);
    callback(); // Our fake Light is synchronous - this value has been successfully set
  });

// We want to intercept requests for our current power state so we can query the hardware itself instead of
// allowing HAP-NodeJS to return the cached Characteristic.value.
light
  .getService(Service.Lightbulb)
  .getCharacteristic(Characteristic.On)
  .on('get', function(callback) {
    
    // this event is emitted when you ask Siri directly whether your light is on or not. you might query
    // the light hardware itself to find this out, then call the callback. But if you take longer than a
    // few seconds to respond, Siri will give up.
    
    var err = null; // in case there were any problems
    
    if (RGBLED.powerOn) {
      console.log("Are we on? Yes.");
//      client.publish('RGBLedPower','1');
      callback(err, true);
    }
    else {
      console.log("Are we on? No.");
  //   client.publish('RGBLedPower','0');
      callback(err, false);
    }
  });

// also add an "optional" Characteristic for Brightness
light
  .getService(Service.Lightbulb)
  .addCharacteristic(Characteristic.Brightness)
  .on('get', function(callback) {
    callback(null, RGBLED.brightness);
  })
  .on('set', function(value, callback) {
    RGBLED.setBrightness(value);
    //client.publish('ledBrightness',String(brightness));
    callback();
  })

light
  .getService(Service.Lightbulb)
  .addCharacteristic(Characteristic.Hue)
  .on('get',function(callback){
   callback(null,RGBLED.hue);
   })
   .on('set',function(value,callback){
   RGBLED.setHue(value);
  // client.publish('ledHue',String(hue));
   callback();   
   })

light
  .getService(Service.Lightbulb)
  .addCharacteristic(Characteristic.Saturation)
  .on('get',function(callback){
   callback(null,RGBLED.saturation);
   })
   .on('set',function(value,callback){
   RGBLED.setSaturation(value);
//   client.publish('ledSaturation',String(saturation));
   callback();   
   })

**Comment by Flawl3ssSWE** [comment]
@TeraJaQ is this for RGB bulbs and if which??

**Comment by TeraJaQ** [comment]
@Flawl3ssSWE no the code is for an rgb led connected on  the NodeMCU
