### ISSUE TITLE
Constantly need to restart Core.js

### ISSUE THREAD

**Issue by ghost** [homebridge/HAP-NodeJS#398]
I just got my first project running with HAP-NodeJS. I'm using GarageDoorOpener_Accessory.js and everything works well... HOWEVER, even though my .JS file is running constantly (No errors) and works as expected, if I leave HomeKit for awhile (15 minutes or so) I am told my device has "no response" so I SSH into my pi, and restart Core.js

Is this a bug? I've tried running Core.js in forever, as well as straight node. Would it be a good idea to just write a script to kill the script and restart it every 15 minutes?

I'm running on a RasPi B+ so I don't want to tax it too hard as the power isn't really there.

Thanks!

**Comment by Maxmudjon** [comment]
Start you HAP-NodeJS at the terminal in wait Error, cover not just wait for the terminal !
I sometimes do and help me )

**Comment by pairughdocks** [comment]
I'm honestly not real sure what to take away from that other than start in terminal and wait for an error. I do not receive any errors, the communication just appears to cease, and then come back randomly. From what I'm reading it could have to do with mDNS.

**Comment by heuels** [comment]
@pairughdocks You can start HAP-NodeJS in debug mode with `DEBUG=* node Core.js`. Even if HAP-NodeJS doesn't throw an error it may print something useful in debug logs.

**Comment by jat80** [comment]
@pairughdocks what type of raspberry pi are you using and more importantly what sort of power supply are you using?

**Comment by Supersimo88** [comment]
I have a similar problem, HAPNodeJs part start without problems after a few hours crashes, if I try to relaunch Core.js seems to start with no problems but the accessories already associated with still do not respond, the only way is to restart the raspberry and It seems to fix this for another couple of hours except the return of the new problem.
I have a raspberry pi B (1) with a more than adequate power supply, also because the same setup worked for months without any problem, then after a node update began to appear similar problems, then I formatted everything and reinstalled from scratch to solve, but at the fifth installation from scratch I am again with HAPNodeJs that crashes.

node v 4.2.1
HAPNodeJs git cloned yesterday

**Comment by zenz** [comment]
same here. any idea to solve this problem?

**Comment by jat80** [comment]
@Supersimo88 @zenz how are you connecting to the network?  Cable or wifi?  Some wifi dongles can cause this problem.

**Comment by zenz** [comment]
@jat80 Hi, I'm using cable to connect my RPi3 to the network.

**Comment by hanandaanom** [comment]
What I did is changed the startup from init.d to systemd. That way it will automatically restart if the node stops responding. I assume that the init.d command would run the node as long as it could, but couldn't tell if the node 'sleeps', because when i use systemctl to check the init.d: it says tht the service is running, yet there are no nodes or services attached to the service.

What works for me is to make a systemd by: 
sudo nano /etc/systemd/system/homekit.service

And then type:
[Unit]
Description=Node.js HomeKit Server 
After=syslog.target network-online.target

Then run 
sudo systemctl daemon-reload
sudo systemctl enable home

[Service]
Type=simple
User=Root
ExecStart=/usr/local/bin/node /home/pi/HAP-NodeJS/Core.js (or BridgedCore.js or CameraCore.js)
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target

**Comment by hanandaanom** [comment]
sudo systemctl enable homekit.service
sudo systemctl start homekit.service

To check you can use sudo systemctl status homekit.service

I need to re-add the accessories, but after that it becomes stable and i don't need to restart it if the node 'sleeps'

This maybe isnt the best solution, but at least it should help from making you restart every now and then

**Comment by hanandaanom** [comment]
What I did is changed the startup from init.d to systemd. That way it will automatically restart if the node stops responding. I assume that the init.d command would run the node as long as it could, but couldn't tell if the node 'sleeps', because when i use systemctl to check the init.d: it says tht the service is running, yet there are no nodes or services attached to the service.
What works for me is to make a systemd by: 
sudo nano /etc/systemd/system/homekit.service

And then type:

 [Unit] 
Description=Node.js HomeKit Server 
After=syslog.target network-online.target

[Service] 
Type=simple User=Root ExecStart=/usr/local/bin/node /home/pi/HAP-NodeJS/Core.js (or BridgedCore.js or CameraCore.js); whichever youre using right now)
Restart=on-failure 
RestartSec=10 
KillMode=process

[Install] 
WantedBy=multi-user.target

Then use:
sudo systemctl daemon-reload
sudo systemctl enable homekit.service
sudo systemctl start homekit.service

To monitor the service:
sudo systemctl status homekit.service

**Comment by Supereg** [comment]
The stale bot seems to be bugged, gonna close it from hand as the issue seems stale.
