### ISSUE TITLE
Apple has opened the HomeKit spec for non-commercial uses

### ISSUE THREAD

**Issue by robbiet480** [homebridge/HAP-NodeJS#457]
It's now available [here](https://developer.apple.com/homekit/specification/), thanks to @maddox for the tipoff. You have to have an Apple Developer Account and accept terms and conditions to download it.

**Comment by maddox** [comment]
:dancer: :dancer: :dancer: 

I hope this means the spec will be stable and new iOS versions won't necessarily break things.

**Comment by davea** [comment]
IANAL but the following text in the license seems quite hostile to open source code:

> 2. Restrictions. You covenant not to (i) use the Specification for any purpose not expressly permitted by this Agreement; (ii) use the Specification to develop or make any device, accessory, software, or other product or service available for distribution to third parties or for commercial sale, lease or license, or otherwise use the Specification, directly or indirectly, for any commercial purpose;

> 9. Nondisclosure and Nonuse of Apple Confidential Information. The Specification is provided to you as “Apple Confidential Information.” Unless otherwise expressly agreed or permitted in writing by Apple, you agree not to disclose, publish, or disseminate Apple Confidential Information to any other person.

**Comment by elvisimprsntr** [comment]
2. Does this simply mean the HAP-NodeJS license agreement needs to be changed to a more restrictive license?

9.  So don't re-publish any Apple documentation

**Comment by mrose17** [comment]
@davea - i, also, am not a lawyer... but after reading those two clauses, it was clear to me that accepting the terms would not allow redistribution for open source. for example, it says "distribution to third parties `or for` commercial sale" not "distribution to third parties `for` commercial sale".

it may very well be that this is just "the lawyers" doing what lawyers have been doing best for decades -- reusing boilerplate -- instead of asking whether the final text serves the advertised purpose. i do not ascribe these actions to either malice or carelessness, i don't know their thinking on the matter.

regardless, if apple computer wants to make this documentation available for use in open source development, then they really ought to be starting with one of the licenses available on github for that purpose.

accordingly,  i most certainly **did not** accept the terms, and instead closed the browser tab, and went on to other things.

**Comment by JangoBritt** [comment]
So essentially, anyone who wanted to implement an official HomeKit HAP instance would have to become a registered Apple developer(£99) to get their own license. That would move the project from open source to community collaboration.

**Comment by pdlove** [comment]
I don't think this will make HAP-NodeJS any more stable because most of the issues we encounter are because the developer using the module is screwing up characteristics. From what I understand the actual HomeKit protocol has had minimal changes since it was released. The trick is that any developer using HAP-NodeJS MUST provide all of the characteristics that are required for a given service.

**Comment by jsmeyers** [comment]
I think that understanding the value of this project is being lost. Utilizing the HomeBridge or HAP-Node.JS for integration with equipment or services that may never get support within the Apple Homekit universe is still a very valuable proposition. I utilize mine for integration of devices that are already EOL and EOS. My stereo or TV will never get Homekit support but I can design and enjoy the integration though this ecosystem.

**Comment by matbor** [comment]
Summary. https://www.theverge.com/2017/6/8/15761800/apple-homekit-updates-ios-11-easier-build-requirements-wwdc-2017

**Comment by justme-1968** [comment]
just some technical things i had already postet in the homebridge thread:
never expected this to happen :)

there is a Color Temperature characteristic documented that is not included in HomeKitTypes.js from HAP-NodeJS. unfortunately it is not useable if a light also supports Hue and Saturation :(

the tlv documentation should help to get logs displayed with eve.

the new services and characteristics that should appear in iOS 11 are not yet included in the document.

**Comment by Hedda** [comment]
"_On top of these updates to make building HomeKit devices easier, Apple is also expanding what HomeKit can do in ways that consumers will notice. It's adding two new categories of supported products, sprinklers and faucets, and it's adding a bunch of new ways to trigger actions at home.

One of the simpler updates, but a favorite of mine, is an enhancement to the sunrise and sunset triggers. Those can now be offset by some amount of time, so you could, for instance, have the lamps in your home turn on shortly before the sun goes down at night._"

Nice!

**Comment by pdlove** [comment]
@justme-1968 I updated the HomeKitTypes.js on my fork last night: https://github.com/pdlove/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js 
It's got everything that is new from Apple's Homekit Accessory Simulator. What the values actually mean are in their public documentation. Color temperature is in Mires and not Kelvin. The conversion is in their doc.

@jsmeyers I would argue the opposite. The value of this project has just been greatly enhanced because we now have documentation on what all of the values actually mean instead of making assumptions and also Apple has now legitimized personal projects. Before I always anticipated the next major update locking out HomeKit connections to unsupported devices but now we know that isn't going to happen so more people may be willing to develop nifty new things with this library.

**Comment by ebaauw** [comment]
> there is a Color Temperature characteristic documented that is not included in HomeKitTypes.js from HAP-NodeJS

And it's supported by the iOS 10.3 builtin Home app!  homebridge-hue will be using it shortly ;-)  

Apple really kept this silent, it's not supported by Eve nor by the v2 Hue bridge.  I've contacted Elgato's tech support, they were very helpful earlier.  I've also posted a message on the Philips Hue developers forum.

There are some other subtle changes as well, see issue #459.

> unfortunately it is not useable if a light also supports Hue and Saturation

That isn't too bad, as both Home and Eve fake color temperature using Hue and Saturation.  I'd expect other HomeKit apps to follow suit.

> the tlv documentation should help to get logs displayed with eve.

Cool, please document what you find out.  Maybe I could add logs for motion and temperature to homebridge-hue.

> Apple is adding temperature triggers, too

I'm happy to see Apple seem to take home automation somewhat more seriously, but this is vastly overhyped.  I've already setup automations based on temperature using a trigger on any change and a condition on the actual temperature value.

**Comment by ebaauw** [comment]
>  I updated the HomeKitTypes.js on my fork last night: https://github.com/pdlove/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js

Great, @pdlove, I was about to.  Could you please add ColorTemperature as optional characteristic to Lightbulb and create a PR?

**Comment by justme-1968** [comment]
> That isn't too bad, as both Home and Eve fake color temperature using Hue and Saturation
the problem is that on the event level you can't find out anymore if the enduser wanted an rgb color or a color temperature. and at least with hue extended color lights it is a difference.

in an other thread someone mentioned that the Color Temperature and Hue/Saturation characteristics are useable simultaneously. even if it is (currently ?) documented otherwise. so i will test.

> Cool, please document what you find out. Maybe I could add logs for motion and temperature to homebridge-hue.

there are already some things known. have a look here: https://gist.github.com/gomfunkel/b1a046d729757120907c and here: 
https://gist.github.com/0ff/668f4b7753c80ad7b60b

**Comment by pdlove** [comment]
@ebaauw I didn't notice Apple's official Accessory Simulator doesn't have it as an associated Characteristic. I wonder what other characteristics are missing. I'll get the PR submitted.

**Comment by ebaauw** [comment]
> in an other thread someone mentioned that the Color Temperature and Hue/Saturation characteristics are useable simultaneously

They are, at least under iOS 10.3.  When editing the colour Home shows two "wheels", one for Colour and one for Temperature.  When a `Color Temperature` characteristic is available, it uses that to set the Temperature, otherwise it uses Hue/Saturation.  For lights with only Color Temperature, Home only shows the Temperature wheel.

**Comment by ebaauw** [comment]
>I didn't notice Apple's official Accessory Simulator doesn't have it as an associated Characteristic. I wonder what other characteristics are missing. I'll get the PR submitted.

Ah, they finally published a new HAS.  Brilliant that that has inconsistencies with the protocol spec.  Although by a quick look at it, just the Color Temperature as optional characteristic for Lightbulb.

Thanks!

**Comment by devbobo** [comment]
@ebaauw @justme-1968 if the `ColorTemperature` characteristic is defined, the Home app uses that instead of faking it using `Hue` and `Saturation` characteristics.

The `ColorTemperature` characteristic can co-exist with the `Hue` and `Saturation` characteristics. The only caveat is that the `Hue` and `Saturation` characteristic values need to be set to zero when the `ColorTemperature` characteristic is adjusted.

**Comment by paulw11** [comment]
@JangoBritt No, the developer program membership just gives you the ability to publish apps on the iOS and Mac app stores.  To get access to HomeKit on commercial terms you need to join the MFi program which comes with its own (much higher) fees, contracts and restrictions.  That wouldn't be suitable for open source development either.  As @mrose17 pointed out, the pesky "or" in the license is the issue; hopefully they may fix that

**Comment by thomaspurchas** [comment]
@pdlove @ebaauw what's the current status of this? It looks like there hasn't been much movement for a month or so now.

@pdlove if time has become an issue for you, I would be happy to fork your fork and work with @ebaauw to get a PR done and merged.

**Comment by ebaauw** [comment]
The PR (#140) is still open.  It's up to Tian to merge it...

@KhaosT do you still have issues with the PR?  How can we help?

**Comment by KhaosT** [comment]
@ebaauw Which PR are you talking about?

**Comment by ebaauw** [comment]
@KhaosT, https://github.com/KhaosT/HAP-NodeJS/pull/460.  Sorry, I must have pasted the wrong link.

**Comment by KhaosT** [comment]
@ebaauw Ah is the PR completed? I told him to ping me when it's ready to be merged and so far he haven't done so.

**Comment by pdlove** [comment]
All updates have been completed. I’ll reevaluate when the production version of IOS 11 is released, but all updates have been applied and all known issues with IOS 11 (or my fixes) have been resolved.
