### ISSUE TITLE
node-persist

### ISSUE THREAD

**Issue by DARYL-fpv** [homebridge/HAP-NodeJS#535]
I need to use node-persist to store the state of each sensor in a non volatile way. As soon as I try to save or retrieve data, the related node behavior become strange....and nothing were saved. Can you help me pls?

**Comment by 0ngar** [comment]
Please, can you help me to solve my issue?
Best regards,
Antonello

**Comment by theopoon** [comment]
Would be helpful if you could explain more on "node behavior become strange", what node version you on, what OS you on, what err you get, and others might be able to help.

**Comment by 0ngar** [comment]
First of all thanks for your reply and sorry for my inaccurate message. I'm running HapNode within an Intel Edison. Using the Core node, I'm simulating several HomeKit devices; 8 directly related to a relays array cabled with the Edison board and two wireless accessories connected through MQTT (mosca). I need to store the state of an accessory locally to the Edison board. I chose to use node-persist but it seems to not work correctly. When I try to store a variable, no error messages were shown but the values are not stored. At the board reboot, trying to load variables from memory, no value were returned.  Let me show you my scratch code: `//https://github.com/simonlast/node-persist/blob/master/examples/counter/counter.js
 
console.log("Starting accessory Relay 1...");
//gpio init
m = require('mraa');
var gpio = new m.Gpio(1); // Select the pin where the led is connected
gpio.dir(m.DIR_OUT);

chalk = require('chalk');

var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;

var storage = require('node-persist');
storage.init({
   // dir: '/home/root/HAP-NodeJS/accessories/persistent-storage/',
	stringify: JSON.stringify,
	parse: JSON.parse,
	encoding: 'utf8',
	logging: false,  // can also be custom logging function
	continuous: true, // continously persist to disk
	interval: false, // milliseconds, persist to disk on an interval
});

// here's a fake hardware device that we'll expose to HomeKit


var RELAY_1 = {
  powerOn: (storage.getItem('state')).toString(),
  brightness: 100, // percentage
  hue: 0,
  saturation: 0,

  setPowerOn: function (on) {
    console.log("Setting Relay 1 as %s!", on? "on" : "off");
    if (on) {
      RELAY_1.powerOn=on;
      gpio.write(powerOn=on?1:0); //cambio stato
	  storage.setItem('state',(RELAY_1.powerOn).toString());
    } else {
      RELAY_1.powerOn = false;
      gpio.write(powerOn=on?1:0); //cambio stato
      storage.setItem('state',(RELAY_1.powerOn).toString());
    };
  console.log(storage.getItem('state'));

  },

  identify: function () {
    console.log("Rele 1 is here!");
    if(RELAY_1.powerOn==true){
    	gpio.write(0); //cambio stato
    	RELAY_1.powerOn = false;
    }else{
    	gpio.write(1); //cambio stato
   		RELAY_1.powerOn = true;
    }
  }
}

// Generate a consistent UUID for our light Accessory that will remain the same even when
// restarting our server. We use the `uuid.generate` helper function to create a deterministic
// UUID based on an arbitrary "namespace" and the word "Rele1".
var lightUUID = uuid.generate('hap-nodejs:accessories:Relay1');

// This is the Accessory that we'll return to HAP-NodeJS that represents our fake light.
var light = exports.accessory = new Accessory('Relay 1', lightUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
light.username = "FA:2B:3C:4C:3E:21";
light.pincode = "069-83-001";

console.log(chalk.red.bgYellow("Scan this code with the \"Home\" app to add the device \"Relay 1\":"));
console.log(chalk.black.bgWhite("                       "));
console.log(chalk.black.bgWhite.bold("       Relay 1         "));
console.log(chalk.black.bgWhite("                       "));
console.log(chalk.black.bgWhite("                       "));
console.log(chalk.black.bgWhite("    ┌────────────┐     "));
console.log(chalk.black.bgWhite("    │ " + light.pincode + " │     "));
console.log(chalk.black.bgWhite("    └────────────┘     "));
console.log(chalk.black.bgWhite("                       "));

// set some basic properties (these values are arbitrary and setting them is optional)
light
  .getService(Service.AccessoryInformation)
  .setCharacteristic(Characteristic.Manufacturer, "ONGAR")
  .setCharacteristic(Characteristic.Model, "Rev-2")
  .setCharacteristic(Characteristic.SerialNumber, "P132KFSHG801");

// listen for the "identify" event for this Accessory
light.on('identify', function (paired, callback) {
  RELAY_1.identify();
  callback(); // success
});

// Add the actual Lightbulb Service and listen for change events from iOS.
// We can see the complete list of Services and Characteristics in `lib/gen/HomeKitTypes.js`
light
  .addService(Service.Lightbulb, "Relay 1") // services exposed to the user should have "names" like "Fake Light" for us
  .getCharacteristic(Characteristic.On)
  .on('set', function (value, callback) {
    RELAY_1.setPowerOn(value);
    callback(); // Our fake Light is synchronous - this value has been successfully set
  });

// We want to intercept requests for our current power state so we can query the hardware itself instead of
// allowing HAP-NodeJS to return the cached Characteristic.value.
light
  .getService(Service.Lightbulb)
  .getCharacteristic(Characteristic.On)
  .on('get', function (callback) {

    // this event is emitted when you ask Siri directly whether your light is on or not. you might query
    // the light hardware itself to find this out, then call the callback. But if you take longer than a
    // few seconds to respond, Siri will give up.

    var err = null; // in case there were any problems

    if (RELAY_1.powerOn) {
      console.log("Are Relay 1 on? Yes.");
      callback(err, true);
    } else {
      console.log("Are Relay 1 on? No.");
      callback(err, false);
    }
  });`

**Comment by 0ngar** [comment]
Is anybody out there? 🧐

**Comment by 0ngar** [comment]
I give up.

**Comment by jvmahon** [comment]
This may be too late to help you, and I'm not certain this is the issue you are having, and I'm guessing 
 bit here, but ...

persist operates asynchronously, so if you try to 'read' too soon after you 'write', then the  'write' may not have completed. Try calling storage.persistSync() before the 'getItem' and I think it will check that the writes have all been completed before the read. Again, I'm not certain this will fix your problem, but its something easy to try.

There is also an option to use the 'promises' version of the persist calls (the version where the calls are followed by .then()  ) as this helps make things synchronous.
