### ISSUE TITLE
Dimmer issues with Homebridge/homeseer

### ISSUE THREAD

**Issue by knaackville** [homebridge/HAP-NodeJS#547]
Just checking over here if there's any thoughts on an issue with dimmers from Homebridge-homeseer (and other plugins).  Turning on a dimmer to 40%, for example, also sends a command to turn the light on.  It appears that the light on command is being received after the dim command.  Something with it HomeKit storing queued events in an unordered hash instead of an ordered array...  Thoughts? 

Link to issue in homebridge area:
https://github.com/nfarina/homebridge/issues/807

**Comment by jvmahon** [comment]
I've been trying to figure out some issues here too.  It seems the homebridge-homeseer plugin uses "100" as the default onValue. However, Z-wave dimmers only use 1-99 for dim levels, 100 is a reserve value and should not be used. Also, if100 is used, then tapping on the icon does not turn on the device (you have to use an onValue of 99 as the maximum), but the light will work if you slide the value on using the dim slider. But this creates another problem which is the sending of the onValue=99 can cause flashing (i.e., a pulsing effect) of the lights when dimming because the plugin sends 99 and then the actual value you want to dim to. This is even worse when you slide the dim slider slowly as you can get multiple "flashes". 

 I've been looking at the homebridge-homeseer-plugin code to try and fix this and what seems to be needed is a check during dimming to see if the light is already on and, if so, not re-send the on value to HomeSeer. However, I'm not sure which lines in the code controls the sending of boty "on" as well as the level signal commands each time you change the level. I'd like to change it so that only the new level is set to HomeSeer if the light is already on.  Another fix may be to send the value of 255 as the onValue as Z-Wave uses this to mean turn the lights on to their last level, so this may result in less flashing of the lights during dimming since you'd be pulsing between the desired dim value and the last set dim value which are likely to be pretty close (at least closer than flashing between the maximum value 99 and the desired value). Any guidance is appreciated.

**Comment by jvmahon** [comment]
I've fixed this as part of an update PR to the homebridge-homeseer-plugin. However, it seems the original author is no longer updating the homebridge-homeseer-plugin, so if you want this update, look at homebridge-homeseer-plugin-2018.  Be sure to read the Readme first as there are a few features / device types in the original plugin which are no longer being supported in this update (e.g., window coverings, garage door openers, and a few others things were dropped since I don't have these devices available to test them).

**Comment by knaackville** [comment]
Your update is working great for me!  Thanks for taking the time to fix this!
