### ISSUE TITLE
Characteristic Useage

### ISSUE THREAD

**Issue by Tkg8455** [homebridge/HAP-NodeJS#584]
Hello
I cannot understand how to use characteristic change. For example
How can I change it  by change on current sensor (or temp sensor) with MCP3008
I found nodejs files to work with MCP3008
But I dont know how to integrate in HAP/NodeJS
Can you give an example code to integrate?
It gets really hard to me to understand whole programming nodejs
Thank you very much

**Comment by Tkg8455** [comment]
Actually. I really try to check them but no understand
Do you know any exact example for these issues

**Comment by NorthernMan54** [comment]
For example, if you were connecting a temperature sensor you could look at the bme280 plugin as an example of how to create a temperature sensor accessory.

https://github.com/rxseger/homebridge-bme280

The easiest approach is to find a plugin that is similar to the accessory you want to create and start there.  And just modify the code to interface with your device, rather than what is there already.

**Comment by Tkg8455** [comment]
Ok. I understand that I will put sensor .js file in HAP-Nodejs folder. I will call this file in the accessory .js file ( I will read values from sensor in accessory .js file). After that I can change the situation of light automatically with using update.characteristic.
Is that true?
Thank you
