### ISSUE TITLE
Force notifications on iOS

### ISSUE THREAD

**Issue by p3ntium** [homebridge/HAP-NodeJS#602]
Hi all:
it's possible to send a notification to iOS for an accessory that not support notifications? For example, a switch cannot show notifications on iOS: It's possible to force on iPhone to show an alert when a switch is pressed?

Regards!!

**Comment by KhaosT** [comment]
Nope.

**Comment by p3ntium** [comment]
oh . :(

And the StatelessProgrammableSwitch? It can receive notifications?
I have a X10 switch as doorbell, and actually it is a Homekit Switch element in HAPNode, and I want to show alerts in iOS when someone rings...

Thanks!!!

**Comment by Supereg** [comment]
StatelessProgrammableSwitch doesn't display notifications since you configure actions for specific events (like single press, double press or hold) and those actions are executed then via HomeKit.
You could probably implement a doorbell service but this service requires a camera.
A bit ugly but you could also create a motion sensor instead, since this is a device which is able to display notifications on your iOS device.

**Comment by KhaosT** [comment]
There is a doorbell service…

**Comment by p3ntium** [comment]
Thanks @Supereg , the motion sensor it's my second option  :)
@KhaosT : The Doorbell service can't be configured lonely into an accessory, right? Is there another way to implement it out of a camera accessory?

Thnks!!

**Comment by Supereg** [comment]
@KhaosT the doorbell service is not supported by the Home App as a standalone accessory. It must be implemented combined with a camera.

**Comment by p3ntium** [comment]
So I think the best choice is through a motion sensor accessory. It has an additional advantage: I have a pipe cam on the main door, if I configure the switch like a motion sensor and merge it in the same room with that cam, when someone touch the switch I will receive a snapshot attached to the notification.... This is a good behaviour...

Regards!!!
