### ISSUE TITLE
ColorTemperature with Hue and Saturation

### ISSUE THREAD

**Issue by AMoo-Miki** [homebridge/HAP-NodeJS#618]
I am trying to get an RGB+TW light work with HomeKit. I have been able to successfully have it show up with all the setting and changing working as expected.

The problems I haven't been able to solve are:
1) When using the Home app to change the color temperature, as soon as the `set` callback is called, the pointer color changes to white (#FFF) despite having the correct value in the characteristic. I have tried both `callback()` and `callback(null, true)` but the effect is the same.
   Odd thing is, if I hold the pointer and let go only after the callback has executed, it holds its color matching the temperature. Triggering a change from outside the Home app and then opening the Home app, I still get the white (#FFF) colored pointer.

2) If I change the hue and saturation on the color dial of the Home app, the white color temperature pointer doesn't show up. However, if I set the hue and saturation for outside the Home app, returning to Home app opens up to the color temperature dial with a pointer that matches the hue and saturation I had set.
  When in color mode, I set ColorTemperature to `0`; I have adjusted the min to `0` and max to `600` on the characteristic to accept the `0` value. When in white mode, I set the Hue and Saturation to `0`.

3) ~~While the Home app is open and the color or color temperature dials are shown, changing the color from outside the Home app, doesn't update the interface. However, if I get out of the color dials, back to the room interface, and open the bulb color dials again, it shows the updated colors. Doing the same for brightness works just fine.~~

I am aware that the HomeKit Accessory Protocol Specification states that color temperature cannot be used along with hue and saturation, but my LIFX bulbs, which support HomeKit natively, work as expected using the Home app. While I don't own a TP-Link bulb, I have seen [plasticrake/homebridge-tplink-smarthome](https://github.com/plasticrake/homebridge-tplink-smarthome/blob/master/lib/bulb.js) employ the same method as I have; I am not sure if their bulbs suffer from the 3 issues in the Home app as me.

If it helps, here is my code: [RGBTWAccessory.js](https://github.com/AMoo-Miki/homebridge-tuya-lan/blob/89e3d9dbfc1ef928230a85acc9390a29e7b99104/lib/RGBTWAccessory.js). I am hoping that this has to do with something that I am doing wrong and that you can point it out to me.

Additionally, if you know of any package that uses color temperature along with color and the Home app handles it correctly, it would be great if you could mention it; I might be able to learn from it.

**Comment by AMoo-Miki** [comment]
Thanks for taking the time too look into this. The 3rd problem was my fault for having a `return` at the beginning of my `change` listener.

The Tuya devices emit the change event and react correctly to all the changes sent from the Home app.

The remaining two problems, 1 and 2, make me think that there might be something that needs to be done to let the Home app know that I am (a) in the color temp mode or color mode, and (b) set the correct color temperature on the dial.

**Comment by NorthernMan54** [comment]
If you manage to figure this out it would be great to know how to do the same.  I’m working on a led strip plugin and have the same user experience.

**Comment by ebaauw** [comment]
In homebridge-hue, I expose enhanced colour lights with both _Color Temperature_ and _Hue_/_Saturation_.  I don't set the other Characteristic(s) to zero, as I've read before would be required to support both on a single _Lightbulb_ service.  In ZigBee, there's an attribute that reports how the light was last set (through mired colour temperature or through CIEE 1931 xy colours), but there's no HomeKit equivalent.  The Philips Hue lights actually update xy when setting colour temperature and v.v. and my plugin sets the HomeKit characteristics to the (converted) value the light reports.

Various HomeKit apps deal with colour/colour temperature differently, but I find I'm always able to set whatever I want.  In Apple's Home, hold the lightbulb tile, choose _Colour_ and the press _Edit_ (the centre circle).  Now you can switch between _Colour_ and _Colour Temperature_.  I Eve there's different controls for colour vs colour temperature on the details of the service.  Under the colour control, you can select _Color_ vs _White_.  When there is a _Color Temperature_ characteristic, the control will use that, otherwise Eve translates the colour temperature to _Hue_/_Saturation_ values.

**Comment by NorthernMan54** [comment]
Tks Erik

When I rolled my own led strip plugin last month I used a similar behaviour and approach.  But the ultimate question is, can we force the behaviour once you select the colour button in the home app, and if in colour mode, got to the colour selector rather than the current behaviour which at least for me goes to the colour temperature selector.

**Comment by ebaauw** [comment]
I’m afraid the only way to do that is to expose the light as two _Lightbulb_ services, one with only _Hue_/_Saturation_, one with only _Color Temperature_.  This doesn’t necessarily make sense for lights with three channels (RGB, like the 1st and 2nd generation Hue bulbs) that create the whites by mixing these, but is quite natural for the five-channel lights (RGB, warm white, cool white).  The GLEDOPTO 5-channel LED driver actually exposes two different ZigBee endpoints, one for RGB and one for WW/CW.

**Comment by NorthernMan54** [comment]
@ebaauw Tks very much Erik

**Comment by ebaauw** [comment]
> My function takes in the value of HomeKit's Color Temperature and gives back Hue and Saturation that can be used for `updateValue`

The Home app will actually do this for you, if you only expose _Hue_ and _Saturation_.  Same for Eve.

> I cannot be happy with having two accessories show up for the same product

It's actually two services for the same accessory.  Apple's Home app is misleading in that it calls the tiles accessories, where they are, in fact, services (except for the stateless programmable switch).

**Comment by AMoo-Miki** [comment]
> The Home app will actually do this for you, if you only expose _Hue_ and _Saturation_. Same for Eve.

True. My function does it when you have all 3 of Hue, Saturation, and Color Temperature exposed.

> It's actually two services for the same accessory. Apple's Home app is misleading in that it calls the tiles accessories, where they are, in fact, services...

True, but an end user wouldn't care to see it that way; the user in me, seeing two identical tiles with almost identical wheels, to control the same light will just go nuts.
