### ISSUE TITLE
How to add manufacturer, serial number and model to accessory.js file?

### ISSUE THREAD

**Issue by Bedzaa** [homebridge/HAP-NodeJS#630]
Hi,
I am totaly new here. Trying to set my homekit based home :-) with NODE JS. Runnig well with lights using Sonoff. 
My help request is : how to set in the accessory.js code the manufacturer, model and serial number?
Attached is my accessory.JS file and screenshot of my issue.
Thank You in advance
[accessory_example.zip](https://github.com/KhaosT/HAP-NodeJS/files/2679371/accessory_example.zip)
![img_4778](https://user-images.githubusercontent.com/45871405/49994459-d7beac80-ff89-11e8-9fda-35d6e7be1ff3.PNG)

**Comment by Bedzaa** [comment]
no one knows?

**Comment by NorthernMan54** [comment]
Have you tried looking at someone’s working code for example’s

    accessory.getService(Service.AccessoryInformation)
      .setCharacteristic(Characteristic.Manufacturer, “My Build")
      .setCharacteristic(Characteristic.Model, model)
      .setCharacteristic(Characteristic.SerialNumber, hostname + "-" + name)
      .setCharacteristic(Characteristic.FirmwareRevision, require('./package.json').version);

**Comment by Supereg** [comment]
As @NorthernMan54 already stated, on every accessory there is already by default the `AccessoryInformation` service added. This service has the characteristics you are looking for and you can change it as mentioned above.
For starter you could also have a look into the HAP (HomeKit Accessory Protocol) specification non-commercial version (downloadable from apple developer website), to get an overview about all available services and characteristics. The specs sheet could be a bit scary for the first time since it also shows how the IP and Bluetooth protocol exactly works, but you can ignore that for the time.
You could also look into the `HomeKitTypes` files in  the [gen folder](https://github.com/KhaosT/HAP-NodeJS/tree/master/lib/gen). In there are all characteristics and services listed. Could be helpful if you are a bit familiar reading javascript code :)

**Comment by Bedzaa** [comment]
Thank You guys. It is obvious I am not skilled in javascript :-) unfortunately. But big step for me things are running at home :-)

Would you suggest to me a code based on my accessory_example.zip file containing one typical accessory I am using for Sonoff smart switch?

That would help me a lot.

Thank You in advance

**Comment by NorthernMan54** [comment]
If your starting out, start with homebridge as there likely is a plugin already developed and available.  If your using sonoff-tasmota then there is homebridge-mqttthing
