### ISSUE TITLE
Reacting to Writing/Reading Multiple Characteristics at once

### ISSUE THREAD

**Issue by plasticrake** [homebridge/HAP-NodeJS#642]
This question is in the context of writing a homebridge plugin for a device.

Is there a way to respond to simultaneous multiple characteristic get/set(s)? For example a a homekit lightbulb may request the current value or change: `On`, `Brightness`, `Hue`, `Saturation` all at once. However the way I know to react to this is:

```js
    this.LightbulbService.getCharacteristic(Characteristic.On)
      .on('get', callbackify(this.getOn))
      .on('set', callbackify(this.setOn));

    this.LightbulbService.getCharacteristic(Characteristic.Brightness)
      .on('get', callbackify(this.getBrightness))
      .on('set', callbackify(this.setBrightness));

...
```

In my case, behind the scenes this requires 4 network sockets and 4 separate commands sent to the device which adds latency and also will sometimes leave the device in an inconstant state if one of the commands fails.

I was hoping there would be a way to listen to batch of characteristic updates so I could send one unified command to the device.

```js
    this.LightbulbService.on('characteristics-get', (callback, characteristics)=>{
      // get values for each characteristic all at once
      let state = getCurrentLightbulbState();
      if (characteristics.On) characteristics.On.value = state.On;
      if (characteristics.Brightness) characteristics.Brightness.value = state.Brightness;
      // ...
      callback(characteristics);
    });
    this.LightbulbService.on('characteristics-set', (callback, characteristics)=>{
      // update all characteristics at once
      setLightbulbState(characteristics.On, characteristics.Brightness, characteristics.Hue, characteristics.Saturation);
      callback();
    });
```

Is there a way to do this currently?

**Comment by ebaauw** [comment]
It's doable, but no help from HAP-NodeJS nor homebridge.  In my homebridge-hue plugin, I collect multiple characteristic changes for the same light into a single command to the Hue bridge myself.  See https://github.com/ebaauw/homebridge-hue/blob/bcf337cd73de5c9f2298c5929acbcaf117d63f09/lib/HueLight.js#L1467-L1513.  The default `waitTimeUpdate` of 20 (ms) seems to work fine.

**Comment by plasticrake** [comment]
Thanks for the example @ebaauw! I was planning on implementing something like that and its good to know a quick wait time of 20ms may be enough.

**Comment by Supereg** [comment]
I could imagine a way of defining SET/GET handlers on a service level, though I'm unsure If we want to introduce this type of 'complexity'. How would we handle the case, when both is defined. Handlers for every characteristic and a "global" service handler at the same time.

If you only want to combine all changes made in a SINGLE hap request, all the handlers would be called in the same tick. You could just save the changes somewhere and schedule a job on the next tick of the event loop to push all changes to your network device. Otherwise if you also want to catch changes made with multiple request arriving shortly after each other, best would be to use some sort of timed scheduler with a fixed time interval as already described above.

As the issue is stale since a long time, going to close it for now.
