### ISSUE TITLE
Service.AccessoryInformation with displayName thows same UUID error

### ISSUE THREAD

**Issue by jonavila** [homebridge/HAP-NodeJS#677]
When creating a new `AccessoryInformation` service with a displayName argument, I receive the following error:

```Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: 00000023-0000-1000-8000-0026BB765291```

It seems like this issue stems from the fact that the Service constructor will create the *Name* characteristic for every service when the displayName is provided:

https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Service.js#L58

Subsequently, the AccessoryInformation service will attempt to add the same *Name* characteristic that has already been added:

https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L2660

I'm building a platform plugin using Homebridge & Typescript and I'm wondering what's the correct way to add the AccessoryInformation service to all my accessories. 

I believe the only workaround at the moment is to omit and the displayName when creating the AccessoryInformation service and to make sure the accessory has a `name` property defined.

FYI @KhaosT

**Comment by Shaquu** [comment]
Try this

accessory
.getService(Service.AccessoryInformation)
.setCharacteristic(Characteristic.Name, displayName);

**Comment by jonavila** [comment]
@Shaquu Part of the problem is that I'm going through Homebridge and not using hap-nodejs directly. Question: Do you know why the name Characteristic gets added to every service if the AccessoryInformation service will be added to all accessories and the *Name* characteristic is required?

**Comment by Shaquu** [comment]
Remember that Homebridge is not the only project using HAP-NodeJS.
Hardcoding is not a good thing like you did in PR.
So either you provide displayName or you don't and you have to add Characteristic.Name manually.

Please provide the code which makes an error for you since I don't get what your problem really is.

**Comment by jonavila** [comment]
@Shaquu Here you go:
https://repl.it/@jonavila/AccessoryInformation-bug

Just open and click Run.

The hardcoding was based on a similar workaround a few lines below in that file for the Firmware Revision characteristic: https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Service.js#L76

**Comment by tobekas** [comment]
Problem is that the Name characteristic is added first in the super constructor (Service) and after this in the Service.AccessoryInformation constructor.
I think the line `getCharacteriatic... || addCharacteriatic...` in the Service super constructor should check if Name already exists, but this will never be the case since all default characteristics and optional characteristic will be added afterwards.

**Comment by tobekas** [comment]
Service.AccessoryInformation is the only service with a required Characteristic.Name. Therefore this bug does not occur for all other services. For them, Name is added (if DisplayName is defined) and after this Name is also added to optionalCharacteristics.

In mq optional, best way is to fix this issue like there for FormwareRevision: https://github.com/KhaosT/HAP-NodeJS/blob/a42102f5db0388b67f28974ca5fa489933ca1be6/lib/Service.js#L77

**Comment by jonavila** [comment]
@tobekas Yeah, that's the conclusion the came to, and I opened a PR with a fix similar to the Firmware Revision characteristic. Happy to change it if there's a better way to do it.

**Comment by tobekas** [comment]
The workaround to omit the displayName argument and set your Name with `infoService.setCharacteristic(Characteristic.Name, myName)` might not work because of these homebridge issue: https://github.com/nfarina/homebridge/pull/2207 / https://github.com/nfarina/homebridge/pull/2169

**Comment by tobekas** [comment]
@ebaauw: Can you have a look at this issue. I know you are HAP specialist, because we discussed about Name characteristics in the past? ;-)
Would be great if you could bring in your knowledge and experience here...

**Comment by Supereg** [comment]
> Question: Do you know why the name Characteristic gets added to every service if the AccessoryInformation service will be added to all accessories and the _Name_ characteristic is required?
@jonavila The reason is that the Accessory Name and the Name of a Service are total different things. Accessory Name is predefined by the Accessory manufacturer and is/should be unique on the Network. The Accessory name is defined through the AccessoryInformation service.
A accessory can have multiple services (like Lights, Switch, Fan) and all of these services can have a different name. Thus the Name characteristics is used.

AccessoryInformation service is mandatory, thus HAP-NodeJS will add it automatically on Accessory creation. A supplied Accessory display name will be automatically set in the AccessoryInformation service (This is also true for the homebridge supplied PlatformAccessory). If you want to change values in the AccessoryInformation service you can just get a reference using `getService`. If you developing a homebridge accessory (not a platform) the ideal way to deal with that is to just return a instance of an AccessoryInformation service in your `getServices()` and homebridge will automatically replace it.

And to reference the original reason the issue was created. You should definitely be able (at least in the latest version of HAP-NodeJS) to create a new instance of the AccessoryInformation service, as the Service constructor check first if the Name characteristic was already added.
