### ISSUE TITLE
Set up a bridge between accessory and Home app

### ISSUE THREAD

**Issue by sszczep** [homebridge/HAP-NodeJS#694]
Hi. I'd like to make some kind of a relay between homekit accessories and home app (I want to log changes and do other stuff). I guess the best way would be to connect to accessories using node and expose them again via homebridge. Do you think it's possible? 

For example:
- normal way: Philips Hue -> Home app on iOS
- my way: Philips Hue -> my app where i log data -> Home app on iOS.

Thanks

**Comment by Supereg** [comment]
Do you want to basically create a HAP proxy?

**Comment by Supereg** [comment]
If a Transparent proxy is the thing you want, you may want to have a look at https://github.com/Supereg/hap-proxy. This project is definitely not finished and not well documented, but has working implementation to intercept traffic between a certified HomeKit accessory.
As the author stopped responding and the issue was answered best as I could, I gonna close it for now.
