### ISSUE TITLE
CameraController.ts Changes

### ISSUE THREAD

**Issue by marcus-j-davies** [homebridge/HAP-NodeJS#812]
Hello,

I see the Hap-NodeJS project has shifted in terms of ownership or something to that affect.
I'm witnessing a real increase in development 👍 

A quick question on the camera implementation.

Im using, what I can only assume, is the now deprecated controller. The new controller I see, has a call back for `handleStreamRequest`

Is this required by HAP, or is this specific to HAP-NodeJS?

I suppose what I am asking - is it recommended I switch to the new controller?.
what is the benefit?

As always - the work here, is astounding, highly appreciated and valued.

**Comment by Supereg** [comment]
> I see the Hap-NodeJS project has shifted in terms of ownership or something to that affect.
I'm witnessing a real increase in development 👍

HAP-NodeJS is now part of the homebridge organization on GitHub and is also maintained by the team, with me currently being the one spending the most time with it 😅 

The new callback is just something HAP-NodeJS introduced. In general you would just call it instantly after you started your streaming source. But it does also open up the possibility to easily cancel the transmission in the last minute by passing an Error instance to the first argument of the callback for the event that you notice, that your streaming source is unable to be started. Otherwise I is also totally fine to just call the forceStop method on the CameraController. It's just a little bit of flexibility added.

Most of the benefits introduced with the new CameraController API are also brought back to the old style CameraSouce API. The big flagship feature is really only needed in the context of homebridge (being serialization and deserialization for dynamic platform plugins to expose a bridged camera).
But in general you really only get a bit of a more streamline configuration, improved types and probably less management code in your CameraSource instance (like you no longer need to create those StreamControllers manually and also support for automatically adding the Speaker and Microphone service was added). And for the future, future support of Secure Video will only be accessible through the CameraController.

So do you need to switch? Not really, but you can of course. Currently there are no plans to remove support for the legacy CameraSource API. On the other hand you basically are already using those new internals.

**Comment by marcus-j-davies** [comment]
Thanks @Supereg !

I'll hold back for now - once secure video becomes implemented, then naturally, it makes sense to switch.

Awesome Work!
