### ISSUE TITLE
Explicitly setting SerialNumber to a blank ('') value breaks HomeKit, renders Accessories unusable

### ISSUE THREAD

**Issue by johannrichard** [homebridge/HAP-NodeJS#824]
By definition,  a blank string (`''`) is a valid `Formats.STRING` value and actually the default value for `undefined` or `null` strings passed when setting any String Characteristic. 

https://github.com/homebridge/HAP-NodeJS/blob/f3f032547f9c21f61c6338fbaf948b8258415012/src/lib/Characteristic.ts#L537-L546

However, if a `SerialNumber` Characteristic of the `AccessoryInformation` Service is deliberately set to `''` (either directly or by passing an `undefined` variable which falls back to blank), HomeKit on iOS 13 stops working (i.e. it won't be able to add the accessory, claiming it can't connect).

I'm not sure if this is by design or an error. I would argue though that the `SerialNumber` Characteristic should either explicitly check for blank values (i.e. through something like an `Formats.NONBLANKSTRING`) or that this caveat is added somewhere in the documentation. I strongly prefer the first solution but don't know what your policy is on that. I couldn't find a specific bug report for that, so I assume it's something unreported, if not, apologies for duplicating.

How to reproduce: 

- Create a simple Homebridge plugin based on https://github.com/homebridge/homebridge-plugin-template
- Set the `SerialNumber` Characteristic of the `AccessoryInformation` to an empty string (`''`) (Edit)
- Run Homebridge and try to add the Accessory to HomeKit --> iOS can't connect

![IMG_3670](https://user-images.githubusercontent.com/32964940/82446150-69e3b200-9aa6-11ea-8cc9-d22af7473ede.png)  

Tested w/ iOS 13.x.

**Comment by Supereg** [comment]
Since HAP-NodeJS v0.6.8 we added a validation function which is called just before the accessory gets published, as we ran exactly in those issues with the homebridge v1.0.0 release.
https://github.com/homebridge/HAP-NodeJS/blob/f3f032547f9c21f61c6338fbaf948b8258415012/src/lib/Accessory.ts#L748

Homebridge additionally should do quite a good job catching those mistakes as well.
But it seems when dealing with DynamicPlatforms you can still change the value after publishment of the bridge and without homebridge noticing it 🤔

**Comment by codyc1515** [comment]
> But it seems when dealing with DynamicPlatforms you can still change the value after publishment of the bridge and without homebridge noticing it 🤔

I don't believe this is supported by the HomeKit spec. It's meant to be static. Easy way to sort that would be not allow it.

**Comment by johannrichard** [comment]
> > But it seems when dealing with DynamicPlatforms you can still change the value after publishment of the bridge and without homebridge noticing it 🤔

I second that. 

> I don't believe this is supported by the HomeKit spec. It's meant to be static. Easy way to sort that would be not allow it.

That’s not clear from the (publicly) available doc, is it? 

However the doc at https://developer.apple.com/documentation/homekit/hmcharacteristic/characteristic_types#topics says FirmwareVersion, SerialNumber, Manufacturer and Model are now all deprecated so it’s probably better to not set them anymore at all (But then I’d argue HAP-NodeJS shouldn’t set them to default values either)?

**Comment by codyc1515** [comment]
The document you're referring to is talking about setting a Characteristic named Manufacturer, as opposed to setting the attribute under the Accessory Information service.

**Comment by Supereg** [comment]
Does somebody know, if there are other characteristics besides SerialNumber which have the same effect?

**Comment by Supereg** [comment]
This issue was addressed with hap-nodejs v0.9.0-beta.19. We will now refuse to set a value to SerialNumber or Model characteristic if the values length is less or equal to 1 character (as specified by the spec). Instead the current value will be used and an error stack trace will be printed to `console.error`.
