### ISSUE TITLE
Home kit resetting accessory?

### ISSUE THREAD

**Issue by Final-Hawk** [homebridge/HAP-NodeJS#831]
Home kit seems so reset my accessory to their default names and rooms and then adds them back to their previous state after 10 minutes. cannot replicate just keeps happening. any ideas?

**Comment by ebaauw** [comment]
> "Home kit seems so reset my accessory to their default names and rooms and then adds them back to their previous state after 10 minutes." would be helpful. I can't really imagine what's happening.

The accessory gets unexposed by Homebridge, causing HomeKit to delete it.  When it gets re-exposed later on, HomeKit treats it as a new accessory, having lost any HomeKit settings, like the name, and any associations to HomeKit rooms, groups, scenes, automations.

Now, what’s causing this is a different question.  In theory it could be a dynamic platform plugin removing and re-adding the accessories.  More likely, a static plugin doesn’t expose the accessory after Homebridge restarts, but re-exposes it on the next restart.  Either case it’s likely a plugin issue, maybe combined with another plugin issue, causing Homebridge to restart.

Could also be caused by deleting (or in case of Docker: not persisting) `cachedAccessories` on Homebridge (container) restarts.

**Comment by Final-Hawk** [comment]
Yes, sorry I should’ve explained it better. There is nothing in the debug logs that indicate anything. This is hap-NodeJs with a contact sensor accessory and a garage door opener accessory. That’s it. When I go into the home app the 2 accessory’s appear at the bottom of the favourites list in default room with their default name specified in the accessory code.  Rebooting doesn’t help, if it’s my router, HomePod or the raspberry pi zero it’s running on. However after 5 minutes or longer it appears in the home app as it’s previous HomeKit assigned name and room, it’s almost like it resets itself to default settings than goes back in time to before it did that. I am running it on bridged core. Will post my code when I get a chance as I am on my phone at the moment. I have reset everything (changed usernames and pairing pins for good measure) and made sure my 1 other hap-nodejs that’s running core.js with 2motion sensor accessories and my homebridge instance don’t have conflicting info.  The other hap-nodejs instance has this issue as well with only 1of the accessories. I will report back to see if the resetting has helped. Thanks for trying to help me!

**Comment by ebaauw** [comment]
Sorry, I should have read better.  Still, running a bridge in HAP-NodeJS is very similar to Homebridge.  If you start the HAP server of the bridge, before exposing the bridged accessories, HomeKit will delete the accessories.  If you then expose the bridged accessories, HomeKit sees them as new accessories.

**Comment by Final-Hawk** [comment]
Ok, thanks for you're help i have reset everything and it seems to be working well. i mainly wanted to post this to see if anyone else has the same issue. I also changed the ports on the hap server. i will reopen if it comes back. Thanks
