### ISSUE TITLE
Depreciation of Core/BridgeCore

### ISSUE THREAD

**Issue by n0rt0nthec4t** [homebridge/HAP-NodeJS#833]
I've just come across this in the latest commit, and not sure what to think. Seems like a retrograde back step and the wiki entry doesn't really seem to justify the move,

Wondering where this was discussed with the community of users of HAP-NodeJS?? Just seems to be focused on borging into HomeBridge...

And why isn't there a pin topic on this?

**Comment by FliegenKLATSCH** [comment]
Instead of letting users add the `publish` to each accessory, why don't you provide/encourage a way to call the feature of `Core.ts`?
I have basically a copy of Core.ts in my code, but it would be nice to have something like:
```
const hap = require('hap-nodejs');
hap.startUp({
  // options like..
  accessoriesDirectory: 'HAP-Accessories',
  storageDirectory: '.',
  targetPort: 51826,
  // ...
});
```

This way the library could also take care of `unpublish`, what Core.ts also does, but the new proposed way does not support?
I don't know if this is an issue, but I recently see some `Error: Service name is already in use on the network` after restart.

**Comment by n0rt0nthec4t** [comment]
I’d also like to know how we can handle multiple accessories running on the same system. From what I can tell, you’d need to run each accessory in a docker container, rather than the load accessory/accessory factory we use now (which is perfect for running multiple de eloped accessories on the one system)

**Comment by Supereg** [comment]
Sorry for taking so long to answer. Honestly I though it was pretty well explained in the wiki page.
It is not really straight forward or easy for the end user to install and it is a hell to maintain compatibility with an ever involving project. You can't really do information hiding, as people can easily import private API.

My current plan (which wasn't announced yet as it is just an idea) is to maybe create some separate project, some sort of hap-nodejs runner, which pretty much acts like BridgeCore and Core, as I saw that there are some people sharing those accessory files. So maybe just create and simple npm package (so its easy to update) which uses a predefined folder which runs the accessory files located inside. this would then be JavaScript only.

I don't know if such a side project is wanted. My though was, as the few lines in Core aren't much (it's really only a .publish call and a signal handler to gracefully shutdown on a CTRL+C) it might be in the interest of the developer anyways to include the code themselves, as having full control on when the .publish function is called might be helpful (at least that is what I saw most of the times, that people wanted to delay the execution of that).

> I’d also like to know how we can handle multiple accessories running on the same system. From what I can tell, you’d need to run each accessory in a docker container, rather than the load accessory/accessory factory we use now (which is perfect for running multiple de eloped accessories on the one system)

If you want to have them bridged by one single accessory, you would just create an additional accessory (the Bridge), add all other accessories to the Bridge and call .publish on the bridge accessory (as seen in BridgeCore). Otherwise you can publish each Accessory on their own. You will just need to specify different ports for each accessory (or use `0` so the operating system will decide on a free port on every start).

> I don't know if this is an issue, but I recently see some Error: Service name is already in use on the network after restart.

This is unrelated.

**Comment by n0rt0nthec4t** [comment]
> My current plan (which wasn't announced yet as it is just an idea) is to maybe create some separate project, some sort of hap-nodejs runner, which pretty much acts like BridgeCore and Core, as I saw that there are some people sharing those accessory files. So maybe just create and simple npm package (so its easy to update) which uses a predefined folder which runs the accessory files located inside. this would then be JavaScript only.

But this is exactly the functionality we have at present, so why change a working thing. I'm in teh group that just writes accessory files and has made it work around the issues you describe about. For delaying the starting of an accessory, you can just use the accfactory loading, returning a null array of created accessories and populate and publish yours as need
