### ISSUE TITLE
Siri brightness %

### ISSUE THREAD

**Issue by kontur11** [homebridge/HAP-NodeJS#870]
When using the Light accessory, I change the Brightness properties-MinValue: 0, MaxValue: 255, everything works correctly with the parameters of my controller in % brightness on the slider. But if you use Siri, it does not set the brightness as a percentage, unlike the slider. Is it a BUG or did I do it wrong? Sorry for my English.

HAP-nodejs 8.5

**Comment by marcus-j-davies** [comment]
Is there a reason you're overwriting the Brightness defaults from 0-100.
The unit for Brightness is PERCENTAGE.

**Comment by kontur11** [comment]
> Is there a reason you're overwriting the Brightness defaults from 0-100.
> The unit for Brightness is PERCENTAGE.
Thanks for the answer, I was confused that the slider still worked as a percentage, but SIRI did not.

**Comment by Supereg** [comment]
Instead of redefining the maxValue, you could just map your 0-255 interval to percentages 0-100.
Like `value = (x/255) * 100 with x in [0, 255]` (maybe you want to have a `Math.round(...)` around that to get an integer value.

While redefining characteristic properties (like min and max value) is possible, not alle Apple defined characteristics are built in a way such that they can adapt properly. 

I assume the issue is solve?
