### ISSUE TITLE
CurrentHeatingCoolingState 'AUTO' value missing

### ISSUE THREAD

**Issue by gorathe** [homebridge/HAP-NodeJS#888]
In HAP-NodeJS/src/lib/definitions/CharacteristicDefinitions.ts the CurrentHeatingCoolingState class is missing an entry for 'AUTO', value 3. The file claims to be autogenerated, but I haven't found what it is autogenerated from yet. This breaks plugins for thermostats that allow both a cool-to set point and a heat-to set point.

```
/**
 * Characteristic "Current Heating Cooling State"
 */
export class CurrentHeatingCoolingState extends Characteristic {

  public static readonly UUID: string = "0000000F-0000-1000-8000-0026BB765291";

  public static readonly OFF = 0;
  public static readonly HEAT = 1;
  public static readonly COOL = 2;

  constructor() {
    super("Current Heating Cooling State", CurrentHeatingCoolingState.UUID, {
      format: Formats.UINT8,
      perms: [Perms.NOTIFY, Perms.PAIRED_READ],
      minValue: 0,
      maxValue: 2,
      minStep: 1,
      validValues: [0, 1, 2],
    });
    this.value = this.getDefaultValue();
  }
}
Characteristic.CurrentHeatingCoolingState = CurrentHeatingCoolingState;
```

**Comment by oznu** [comment]
![image](https://user-images.githubusercontent.com/3979615/109641929-6d17dc80-7ba6-11eb-9098-15f14862ed9c.png)

**Comment by Supereg** [comment]
Duplicates https://github.com/homebridge/HAP-NodeJS/issues/885, https://github.com/homebridge/HAP-NodeJS/issues/815

Note, the validValues for the `CurrentHeatingCoolingState` never changed, so it definitely didn't break anything, because it didn't change [do happy if you can more precisely specify what exactly is "broken"].
Latest 0.9.x release just highlights misconfiguration in plugin code.

The whole thing is best explained already in https://github.com/homebridge/HAP-NodeJS/issues/885#issuecomment-782880351.

**Comment by gorathe** [comment]
Thanks for the clarification folks!
