### ISSUE TITLE
Linking Stateless Programmable Switch with a Service Label

### ISSUE THREAD

**Issue by jvmahon** [homebridge/HAP-NodeJS#889]
I  am trying to create some StateLessProgrammableSwitch buttons which will be added to a dimmer device as another service. This is being done to simulate the Central Scene Buttons of Z-wave devices.

I'm a little unsure of how to "link" each StatelessProgrammableSwitch to the Service label. Is it as simple as setting each switches ServiceLabelIndex as I've show in the following (simplified) code or do I need to do anything elseto form the "link" between the service and the label?

`````
var thisServiceLabel = new Service.ServiceLabel()
thisServiceLabel.getCharacteristic(Characteristic.ServiceLabelNamespace).updateValue(1)
services.push(thisServiceLabel);	

var statelessSwitch
var buttonCount = 2
var buttonNo
		
for (buttonNo = 1; buttonNo <= buttonCount; buttonNo++)
{
	statelessSwitch =  new Service.StatelessProgrammableSwitch("ButtonNo", buttonNo)		

	statelessSwitch.getCharacteristic(Characteristic.ServiceLabelIndex).setValue(buttonNo)
		
	services.push(statelessSwitch);
}
`````

**Comment by ebaauw** [comment]
That should do the trick.

**Comment by jvmahon** [comment]
Thanks. It seems to work. Another question - Sometimes when an accessory has multiple services, they all appear as a single tile and when you go to the details page (gear) of the accessory, you can swipe up/down to see the different services. I was hoping to add these stateless switches to a lightbulb accessory and be able to do that. It seems I either have to show the light and buttons as separate tiles, or if I do group them as a single tile, the buttons become hidden and inaccessible. Any way to show the buttons as part of another service (i.e., a light) without having to use separate tiles? Thanks.

**Comment by ebaauw** [comment]
In my experience Apple’s Home app is totally unpredictable here, especially since the changes in iOS 14.  When I expose a (stateful) _Switch_ and a _Temperature Sensor_ on the same accessory, it combines them in a single tile, irrespective of the _Show as multiple tiles_ setting.  Because of this, I cannot control the switch from the tile, it always pops up the details window.  The _Stateless Programmable Switch_ and _Service Label_ services are always shown as a separate tile.  By the time you think you’ve figured it out (and changed your code), they release a new version which behaves completely differently.

**Comment by jvmahon** [comment]
Thanks!
