### ISSUE TITLE
Critical floating point error on Characteristic Set

### ISSUE THREAD

**Issue by OrigamiDream** [homebridge/HAP-NodeJS#955]
### Analysis

In characteristics like `RotationSpeed` and `Brightness`, we can set the value ranges and the minimum step size.
For instance, an Air Purifier have 6 levels of fan speed, we can set value ranges of RotationSpeed min:0, max:100, and step:16.666... as first option, or min:0, max:6, step:1 as second option.

However, the second option is not working properly with Siri.
The Siri says the value as is, 1%, 2% and 6% max.
To let the Siri works properly, I have to use the first option.

The problem starts here.
If I set the characteristic value manually, the Homebridge runtime changes the value arbitrarily to fit the `minStep` size.
And this must not to be happened.

Details in `Steps to Reproduce`

### Expected Behavior

Characteristic setup:
```typescript
const STEPS = (100 / 6);

service.getCharacteristic(Characteristic.RotationSpeed)
    .setProps({
        minValue: 0.0,
        maxValue: STEPS * 6,
        minStep: STEPS
    })
    .on(CharacteristicEventTypes.SET, (value, callback) => {
        this.log.debug('RotationSpeed SET value', value);
    });
```

Try to change the characteristic value manually using `service#setCharacteristic` for 0 to 100.

`setCharacteristic(RotationSpeed, STEPS * 1)`, expected: 16.6666.., actual value: 16.6666..
`setCharacteristic(RotationSpeed, STEPS * 2)`, **expected: 33.3333.., actual value: 16.6666..**
`setCharacteristic(RotationSpeed, STEPS * 3)`, **expected: 50.0, actual value: 33.3333..**
`setCharacteristic(RotationSpeed, STEPS * 4)`, expected: 66.6666.., actual value: 66.6666..
`setCharacteristic(RotationSpeed, STEPS * 5)`, **expected: 83.3333.., actual value: 66.6666..**
`setCharacteristic(RotationSpeed, STEPS * 6)`, **expected: 100.0, actual value: 83.3333..**

### Steps To Reproduce

1. Create a sample plugin with `AirPurifier` service and `RotationSpeed` characteristic.
2. Set props — minValue: 0, maxValue: 100, minStep: (100 / 6).
3. Try to change the value manually via `service.setCharacteristic()`.
4. Restart the process if the issue does not happen (because floating point precision value changes every process restart in this example)

### Logs

```markdown
This is mathematical and computational issue, no logs.
```

### Configuration

```json
No specific configuration needed
```

### Environment

- OS: Raspberry Pi (5.15.32-v8+)
- Software: 1.4.1
- Node: 16.15.0
- npm: 8.5.5

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

oznu/homebridge:ubuntu

**Comment by adriancable** [comment]
@OrigamiDream (cc: @Supereg ) - thanks for finding this mistake. But, your solution cannot possibly be correct. Main reason being that it doesn't respect minValue and maxValue. So if you take your own example with `STEPS = (100 / 6)`, but set `maxValue` to 83, using your input of `STEPS * 1 ... STEPS * 6` gives an output of:

```
[
  16.666666666666668,
  33.333333333333336,
  50,
  66.66666666666667,
  83.33333333333334,
  83.33333333333334
]
```

which as you can see exceeds the set maxValue. Even if this doesn't happen, your algorithm can still produce the wrong values, because it truncates the input range before rounding, which is backwards. For example, with `maxValue` set to 80 your algorithm produces:

```
[
  16.666666666666668,
  33.333333333333336,
  50,
  66.66666666666667,
  66.66666666666667,
  66.66666666666667
]
```

which isn't right for the last 2 values.

What's wrong with the 'textbook' rounding algorithm and just using this single one-liner (*before* truncating the input range, not after):

```
value = stepValue * Math.round((value - numericMin) / stepValue) + numericMin;
```


That always gives the right answers, right?

**Comment by OrigamiDream** [comment]
Good morning, @adriancable 

Thank you for your analysis.
I cannot reproduce the second approach with my code.
Would you please let me know what environment you had used to test?

About the first approach,
I moved the rounding lines in front of clamping lines, and I have rewritten the entire code of unit test to test all possible approaches which can be happened between 0 and 100.
With one minor fix, the test passes, which means your second approach haven't been happened.

I have created a new PR, we may can talk about this more.
- #958

**Comment by adriancable** [comment]
Hi @OrigamiDream - can you kindly send me an email at adrian.cable@gmail.com and I'll share my code with you there, for the 2nd case? Then we can work on / edit the new PR as necessary once we agree on the correct approach. (The back and forth prior to that probably isn't of interest to most people on the HAP-NodeJS Github.)

**Comment by OrigamiDream** [comment]
Hi @adriancable , Thank you for a suggestion.

I agree to your opinion certainly, which is my suggestion looks like quite complex relatively.
However, you must know that the algorithm was already 10 lines long before I have touched on it.
And the epsilon constant, it was just a constant which gives stability.

In your 'textbook' algorithm, the `numericMin` is useless.
Final results can be wrong in certain conditions because it's a kind of 'offset.'

Anyway
I have slept on the algorithm and this new solution would be better.
```
value = Math.round(value / stepValue) * stepValue;
```
The new one does not have to be changed for specific conditions, like what one of your team did.
And doesn't need to add a mysterious epsilon like what I did.
It's most generalized form in computational way which meet to every conditions.

If you have enough time to review the case, I recommend you to test this out.
However, since I cannot update my plugins because of this hilarious issue, I hope you to review this as soon as possible.

**Comment by adriancable** [comment]
Sorry, but this is wrong. With `minStep: 1`, `minValue: 0.5`, `maxValue: 2.5` the allowable values are clearly 0.5, 1.5, 2.5. Your algorithm allows 0.5, 1, 2, 2.5 which makes no sense.

**Comment by OrigamiDream** [comment]
I understand what you want to say.

The calibrated values were 0.5, 1, 2 and 2.5 so far, so I wanted to keep the legacy support in the algorithm.
However it seems you want to fix them all whatever how plugin developers had implemented.

If you really want to do that, I'll accept your suggestion immediately.

And this is a new suggestion:
The Apple HomeKit only supports 'percentage' in certain slider controllers like Brightness and Rotation Speed.
In my opinion, there must be an algorithm which translate values into 0~100% between HAP-NodeJS and the HomeKit protocol to avoid Siri to saying 1%, 3%, which makes no sense.

There are 3 possible choices:
- Let the developers apply the algorithm manually as before
- Force to apply the algorithm to provide reliable action (especially Siri)
- Give the developers option like to turn on and off the automatic range translation.

**Comment by adriancable** [comment]
If characteristics like Brightness and RotationSpeed are meant to be specified as percentages, the plug-in author should respect that. There isn't any need for HAP-NodeJS to do any conversion or 'automatic range translation'.

The only thing HAP-NodeJS needs to do is round correctly, respecting minStep, minValue and maxValue. The current code in HAP-NodeJS does not do that correctly. Neither do either of your PRs. I appreciate you finding an issue in the HAP-NodeJS code, thank for you that, but - sorry for being blunt, neither of your PRs should be merged because they add complexity and replace 1 corner case failure mode with 3 corner case failure modes. If you want to fix the issue, I have told you how to do this with 1 line of code, otherwise the code should be left alone.

cc: @oznu
